### ISSUE TITLE
gamess-us and gamess are the same project

### ISSUE THREAD

**Issue by yurivict** [repology/repology-rules#102]
```-us``` is a suffix denoting the fork.
It's best if the meta project would be called ```gamess-us``` because ```gamess-uk``` might be eventually created too.

**Comment by AMDmi3** [comment]
Why should a fork be merged?

**Comment by yurivict** [comment]
```gamess-us``` and ```gamess``` are the same project, from the same fork, same codebase.
The divergent fork ```gamess-uk``` doesn't have any packages.

**Comment by AMDmi3** [comment]
I don't see where -us comes from at all.

**Comment by AMDmi3** [comment]
It's not the best idea to invent nonexisting things and then ask to normalize them.
