### ISSUE TITLE
Gentoo needs more package splits

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-rules#11]
Need to be split:
- [x] btf (dev-java and sci-libs)

Actually, a lot more:

```
find gentoo.git -type d -maxdepth 2 -mindepth 2 |
   egrep -v 'dev-(perl|python|haskell)' |
   awk -F/ '{print $NF}' |
   sort | uniq -d
```

- [x] ace
- [x] acl
- [x] ada
- [x] amap
- [x] analog
- [x] apel
- [x] atlas
- [x] attica
- [x] auctex
- [x] baloo
- [x] balsa
- [x] barcode
- [x] bbdb
- [x] bfm
- [x] binclock
- [x] bluedevil
- [x] bson
- [x] btf
- [x] build
- [x] c-support
- [x] calc
- [x] calendar
- [x] cdcover
- [x] cdrtools
- [x] charm
- [x] checkpassword
- [x] coffee-script
- [x] color
- [x] crystal
- [x] csv
- [x] daemontools
- [x] dash
- [x] dictionary
- [x] dirdiff
- [x] docker
- [x] dolphin
- [x] ebuild-mode
- [x] ecb
- [x] eject
- [x] elib
- [x] emacs
- [x] ess
- [x] exo
- [x] fam
- [x] fcgi
- [x] ffmpeg
- [x] fuse
- [x] gambit
- [x] gdl
- [x] git
- [x] glade
- [x] glu
- [x] gnupg
- [x] gnuplot
- [x] gom
- [x] gpgme
- [x] grip
- [x] gsasl
- [x] haskell-mode
- [x] highline
- [x] icecream
- [x] igrep
- [x] info
- [x] jack
- [x] jal
- [x] jama
- [x] jde
- [x] jpeg
- [x] json
- [x] kactivities
- [x] kde-gtk-config
- [x] kdeplasma-addons
- [x] kdesu
- [x] kfilemetadata
- [x] kglobalaccel
- [x] khotkeys
- [x] kinfocenter
- [x] kmenuedit
- [x] knewstuff
- [x] krunner
- [x] kscreen
- [x] kstart
- [x] ksysguard
- [x] kwin
- [x] kwrited
- [x] languagetool
- [x] launchy
- [x] lemon
- [x] libelf
- [x] libffi
- [x] libgudev
- [x] libiconv
- [x] libintl
- [x] libkscreen
- [x] libnet
- [x] libusb
- [x] locale
- [x] lookup
- [x] lzma
- [x] magic
- [x] mailcrypt
- [x] mailx
- [x] man
- [x] mars
- [x] mash
- [x] mavros
- [x] mc
- [x] mediawiki
- [x] mew
- [x] milou
- [x] mime-types
- [x] mldonkey
- [x] mmix
- [x] mmm-mode
- [x] modutils
- [x] mongo
- [x] mpack
- [x] mpc
- [x] msgpack
- [x] muse
- [x] mysql
- [x] nagios
- [x] nemesis
- [x] ninja
- [x] nitrogen
- [x] notification-daemon
- [x] nut
- [x] ocaml
- [x] openmsx
- [x] otter
- [x] pam
- [x] par
- [x] pcl
- [x] pdv
- [x] picard
- [x] pkgconfig
- [x] planner
- [x] plasma-mediacenter
- [x] plasma-nm
- [x] plasma-workspace
- [x] pmake
- [x] pms
- [x] polkit-kde-agent
- [x] polyglot
- [x] powerdevil
- [x] psgml
- [x] psi
- [x] python-mode
- [x] rails
- [x] re2
- [x] redis
- [x] reduce
- [x] riece
- [x] ruby
- [x] rubygems
- [x] screen
- [x] session
- [x] shadow
- [x] signify
- [x] silo
- [x] ski
- [x] skkserv
- [x] slim
- [x] slurm
- [x] smack
- [x] sml-mode
- [x] snappy
- [x] spice
- [x] spin
- [x] splat
- [x] splice
- [x] sqlite3
- [x] ssh
- [x] surf
- [x] systemsettings
- [x] szip
- [x] teco
- [x] texinfo
- [x] tf
- [x] time
- [x] tokyocabinet
- [x] tornado
- [x] tree
- [x] uclibc
- [x] udev
- [x] vc
- [x] vm
- [x] w3m
- [x] xclip
- [x] xslide
- [x] xsp
- [x] yacc
- [x] zenburn
- [x] zenirc

**Comment by jonasstein** [comment]
`app-portage/gentoopm` provides a python module to work on package names and metadata fast and efficient. This could help you a lot to grep the required data.
upstream sources are here: https://github.com/mgorny/gentoopm/
You use it after `import gentoopm`. If you are interested, I can send you code examples.

**Comment by AMDmi3** [comment]
I don't think anything particularly complex is needed here, it's just a plain list of candidates for some split rules.

**Comment by blshkv** [comment]
there are more categories with the same package name, for example:
https://repology.org/metapackage/peach/versions (app-fuzz)
https://repology.org/metapackage/websocket/versions (app-emacs and dev-go).

I think it's better to map categories of different distribution and just respect it during comparasing
