### ISSUE TITLE
pentoo:qt-py -> qt.py

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#111]
https://repology.org/metapackage/python:qt-py/versions
https://repology.org/metapackage/python:qt.py/versions

Gentoo does not allow "." in the filename so we used "-" instead. 
I have created a manifest file https://github.com/pentoo/pentoo-overlay/blob/master/dev-python/qt-py/metadata.xml as an attempt to guide repology but it did not work.

Could you help to mark it as "qt.py" package please?

**Comment by AMDmi3** [comment]
> btw, the next thing is its versioning. The upstream used 1.2.0.b2 but the closest name under Gentoo would be "1.2.0_beta2.ebuild". Please help to adjust rules as well.

Should not be a problem. libversion does not differentiate separators, so `_` is the same as `.` and it only uses the first letter from the alphabetic part, so `b` is the same as `beta`.

Unlike libversion though, repology itself does care for `beta` over `b`, as it allows to mark to mark the version as devel, which would affect `b2` too.

Summarizing, just merging these two packages will in fact fix the version handling, so beta would be devel and 1.1.0 would be the latest.

**Comment by blshkv** [comment]
> Summarizing, just merging these two packages will in fact fix the version handling, so beta would be devel and 1.1.0 would be the latest.

I'm not sure if I got you right, but the b2 is not marked as devel currently:
https://repology.org/metapackage/python:qt.py/versions

**Comment by AMDmi3** [comment]
Correct. There needs to be `beta` compared equally for this to happen.
