### ISSUE TITLE
'agda' and 'haskell:agda' should be the same package

### ISSUE THREAD

**Issue by yurivict** [repology/repology-rules#112]
They are the same Haskell project, just one is without the ```haskell:``` prefix.

**Comment by yurivict** [comment]
PS: You may want to run a speculative query against your database to find all different packages that have the same name when prefixes are removed that also have the same latest version. You are likely to find a some other situations like this one.

**Comment by AMDmi3** [comment]
> PS: You may want to run a speculative query against your database

I've decided to not waste time on this and rather rely on people reporting problems for projects they are interested in.
