### ISSUE TITLE
Search doesn't return 'libmatheval1'

### ISSUE THREAD

**Issue by yurivict** [repology/repology-rules#113]
Debian search for ```libmatheval``` returns ```libmatheval1``` (with ```1```):
https://packages.debian.org/search?suite=all&searchon=names&keywords=libmatheval
but repology doesn't return it:
https://repology.org/metapackages/?search=libmatheval&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=

I don't know why did Debian create the "1" flavor of it, but shouldn't repology show it too when it exists in Debian?

**Comment by AMDmi3** [comment]
https://packages.debian.org/search?suite=all&section=all&arch=any&searchon=sourcenames&keywords=libmatheval
