### ISSUE TITLE
few packages marked as "untrusted" - false positive: 

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#124]
https://repology.org/metapackages/?inrepo=gentoo_ovl_pentoo&outdated=1
the first one https://github.com/jgraph/jgraphx/releases
The latest release is 3.9.10. However, the release 3.9.7 is marked as "untrusted".

https://rubygems.org/gems/oj/versions/3.7.4
this official version is in that list, and so on.

Could you check it among with others packages please?

**Comment by AMDmi3** [comment]
That was a major fuckup, now fixed.
