### ISSUE TITLE
Why is scribus 1.4.7 outdated?

### ISSUE THREAD

**Issue by ryantm** [repology/repology-rules#126]
https://repology.org/metapackage/scribus/versions

Why is 1.4.7 marked outdated and 1.4.6 is marked as the latest? I don't see any specific `scribus` rule here that would cause this.

**Comment by AMDmi3** [comment]
Because of bad wikidata entry, now removed.

**Comment by ryantm** [comment]
Thanks for fixing it. For reference, it looks like it had a bad publication date which AMDmi3 fixed in this edit: https://www.wikidata.org/w/index.php?title=Q8295&type=revision&diff=811832516&oldid=801428659
