### ISSUE TITLE
Merge KDE Telepathy names

### ISSUE THREAD

**Issue by Kaffeine** [repology/repology-rules#161]
`ktp-` and `telepathy-kde-` is the same project. 

https://repology.org/project/ktp-text-ui/versions
https://repology.org/project/telepathy-kde-text-ui/versions

Also please add [ktp-call-ui](https://repology.org/projects/?search=ktp-call-ui) to `kde.yaml`.

**Comment by AMDmi3** [comment]
What are these, what target name is preferred, how is this related to kde.yaml?

**Comment by Kaffeine** [comment]
https://github.com/repology/repology-rules/blob/master/800.renames-and-merges/kde.yaml#L265

```
    ktp-accounts-kcm|
    ktp-approver|
    ktp-auth-handler|
    ktp-common-internals|
    ktp-contact-list|
    ktp-contact-runner|
    ktp-desktop-applets|
    ktp-filetransfer-handler|
    ktp-kded-module|
    ktp-send-file|
    ktp-text-ui|
```
Those packages are usually named `ktp-` but some distros ship them as `telepathy-kde-`.
The list is incomplete — there is also `ktp-call-ui`.

**Comment by AMDmi3** [comment]
These do not seem to belong to kde regexp. It would be better to merge them with single separate rule, as the pattern is quite determinate.

**Comment by Kaffeine** [comment]
Thank you!
