### ISSUE TITLE
ravenports + firefox

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-rules#162]
Some time ago, "rustless-firefox" was moved from unique ports (it was fine there) to under the firefox package.  ok.  Then later, the latest firefox was added to ravenports.  That should have resulted in firefox being removed from "outdated" list, but it didn't.
It shows green for the version 65.0.2 (the latest as of now) and red for version 52.9.0.

I believe this is an error -- rustless-firefox should be treated as an older version of firefox (similar to postgresql, etc).

**Comment by jrmarino** [comment]
I am not sure if this fix is exactly right.
After it went into effect, the firefox ravenports package shows two versions: firefox and rustless-firefox (as expected).
What wasn't expected is that "rustless-firefox" is once again considered a unique package.
I'm not sure how it can appear on both the unique package list and be part of the firefox package, but apparently it's possible.

**Comment by AMDmi3** [comment]
There's no unique package. It only appears as part of `firefox`.
