### ISSUE TITLE
armitage{-bin}: merge two versions

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#165]
Hi, could you please suggest a solution.

We provide both net-analyzer/armitage-20160709 (this is an unofficial snapshot from https://github.com/rsmudge/armitage) and net-analyzer/armitage-bin-20150813 (the only official binary version available via http://www.fastandeasyhacking.com/download/). 

Repology flags the binary as outdated. How can I remove it from Pentoo outdated list:
https://repology.org/projects/?inrepo=gentoo_ovl_pentoo&outdated=1

**Comment by AMDmi3** [comment]
I'm not sure on correct solution here. I guess it would be easiest to mark this `noscheme`, as there are no tags and the 08.13.15 scheme is braindead and not followed therefore anyway. Otherwise, all versions apart from AUR would have to be marked incorrect.
