### ISSUE TITLE
False outdated cran modules

### ISSUE THREAD

**Issue by Chocimier** [repology/repology-rules#167]
For cran modules PLD and Void replace dash with `r` letter in version. In Void it is because dash is not allowed in version, and is [well settled](https://github.com/void-linux/void-packages/blob/master/common/environment/build-style/R-cran.sh). Can repology recognize that pattern and not mark packages outdated, e.g. [r:dichromat](https://repology.org/project/r:dichromat/versions)?

**Comment by Chocimier** [comment]
Thanks.

**Comment by AMDmi3** [comment]
:ok_hand:
