### ISSUE TITLE
All http?://*.mepis.org/* URLs redirect to a review site. MEPIS is dead.

### ISSUE THREAD

**Issue by ackalker** [repology/repology-rules#178]
Found while browsing Repology looking for [information](https://repology.org/project/1-to-1-voice-antix/information) on package `1-to-1-voice-antix`: Listed homepage, http://antix.mepis.org/ , redirects to https://www.bestsevenreviews.com/best-linux-distros/ .
Found that http://www.mepis.org/ redirects there as well. Wikipedia [article on MEPIS](https://en.wikipedia.org/wiki/MEPIS) indicates that the MEPIS set of distributions is dead. Perhaps these URLs should be marked as problematic in Repology so distro maintainers can take notice.

Google "antix linux" turns up a site, https://antixlinux.com/ , for which Google's description looks promising, but when I followed the link, I reached an error page: "Error establishing a database connection". I get the same error following a link to a download page on the same site which I found elsewhere.

**Comment by AMDmi3** [comment]
Relevant issue: repology/repology-linkchecker#17, looks like it's time to implement it.

**Comment by AMDmi3** [comment]
Done

**Comment by ackalker** [comment]
Thanks!

Op ma 29 apr. 2019 17:20 schreef Dmitry Marakasov <notifications@github.com
