### ISSUE TITLE
Merge all -legacy suffixes and compat- prefixes

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-rules#19]

**Comment by AMDmi3** [comment]
Package name suffix is not relevant. The only way is to provide the latest version as well, in which case older version will be classified as _legacy_ instead of _outdated_.

**Comment by barracuda156** [comment]
That does not seem to always work. For example, Macports’ `ghc-bootstrap` is marked outdated here: https://repology.org/project/ghc/versions
However it is retained and pegged at 7.6.3 version on purpose (the last one currently working on `ppc`): https://ports.macports.org/port/ghc-bootstrap/details
And Macports does have `ghc` port which tracks current releases (with some delay, but it is reasonably up-to-date): https://ports.macports.org/port/ghc/details

**Comment by AMDmi3** [comment]
There are mechanisms which intentionally prevent described behavior - such as flavors (older version is still outdated if the newer version is different flavor or part of a project) and branches (older version is still outdated if it belongs to legacy branch, but is not latest in that branch). gdc-bootstrap is a flavored in this case, which I suspect may be incorrect.

**Comment by AMDmi3** [comment]
I've recently merged a bunch of -legacy projects and don't plan to spend any more time on proactive merging this (anything can still be merged on request). Less than 100 projects with `compat-*` or `*-legacy` patterns remain, many of which are either valid projects with such names, unprefixed python modules or irrelevant rare projects.

https://repology.org/projects/compat-/?search=compat-
https://repology.org/projects/?search=-legacy
