### ISSUE TITLE
Merge rusty-diceware from void with diceware from crates.io

### ISSUE THREAD

**Issue by jcgruenhage** [repology/repology-rules#212]
https://repology.org/project/rusty-diceware is the same as https://crates.io/crates/diceware, they should be merged. I can't even find the second one on repology though.

**Comment by AMDmi3** [comment]
> I can't even find the second one on repology though.

Modules (from crates.io, pypi, rubygems etc) are hidden unless they are packaged anywhere else, as there's too many of them. You can see them as **Related** in many cases though.

**Comment by jcgruenhage** [comment]
This one is packaged on void, so how would I merge the two?

**Comment by AMDmi3** [comment]
I just did, it'll take effect on the site with the next update.

**Comment by jcgruenhage** [comment]
Oh right, didn't see that commit. Thanks!
