### ISSUE TITLE
Handling WireGuard kernel module versions

### ISSUE THREAD

**Issue by awilfox** [repology/repology-rules#218]
Hi,

In Adélie we call our WireGuard kernel module `wireguard-module-$kver`.  In PLD they call it `wireguard-kernel`.  RPM Fusion calls it `wireguard-kmod`.  Should I write a PR that merges all these packages into a single kernel:wireguard or kmod:wireguard or similar?

**Comment by AMDmi3** [comment]
Yes, please. These all should be merged into plain `wireguard` as it's already done for `-dkms`, since kernel module is not a separate project.
