### ISSUE TITLE
Figure out what's going on with pyyaml

### ISSUE THREAD

**Issue by luzpaz** [repology/repology-rules#225]
https://repology.org/project/python:pyyaml/related  
need to tease apart the differences.

Edit: sorry for the vague ticket. I was rushing and didn't want to forget I found this. Essentially there are different versions here and they may either need to be consolidated all in to one or split up. But I'm confused at what the differences are  ATM. I can take a better look tomorrow.  
Example: all the libyaml derivatives are consolidated in to `libyaml`. While all the rest are consolidated in to `python:pyyaml`

**Comment by AMDmi3** [comment]
What is this?

**Comment by luzpaz** [comment]
Edited first post

**Comment by AMDmi3** [comment]
I don't see any problems here. There are separate libyaml and pyyaml projects + purposely unmerged mingw bits (see #10) + unmerged Python module from Mer (likely needs a wildcard rule extension for Mer).

**Comment by luzpaz** [comment]
Oh ok, #10 clears that up. So just the wildcard for Mer then. Cool. Should I close this ticket or do you want to close it when you add the Mer wildcard?

**Comment by AMDmi3** [comment]
The latter. Thanks!
