### ISSUE TITLE
opencascade v7.3.0p3 == v7.3.3

### ISSUE THREAD

**Issue by luzpaz** [repology/repology-rules#228]
Ubuntu/Debian/Devuan have named the patch version as a minor version

[![Packaging status](https://repology.org/badge/vertical-allrepos/opencascade.svg)](https://repology.org/project/opencascade/versions)

How do I add that to https://github.com/repology/repology-rules/blob/master/900.version-fixes/o.yaml#L39 ?

**Comment by AMDmi3** [comment]
You don't. You should add a separate pair of rules, one marking 7.3.3 from debuntu as incorrect, and another marking everything from debuntu as untrusted. The examples are all over the 900 ruleset.

**Comment by luzpaz** [comment]
I don't think it should be considered fake though. I think they should both be valid. It most likely has to do with the debuntu strict naming schemes and that is why it was release as a minor version

**Comment by AMDmi3** [comment]
It **is** fake. Debian has no problems with p* versions, see bind [![Debian Stable package](https://repology.org/badge/version-for-repo/debian_stable/bind.svg)](https://repology.org/project/bind/versions) for example, and even if it had, another compatible scheme could be used. Under no circumstances skipping a version component in the middle is valid.

**Comment by luzpaz** [comment]
CC @kkremitzki

**Comment by kkremitzki** [comment]
The problem is that `dpkg --compare-versions 7.3.0p3+dfsg1 lt 7.3.0+dfsg1` evaluates to true, i.e. dpkg considers it to be a lower version.

**Comment by AMDmi3** [comment]
And `7.3.0.p3+dfsg3`? It's true that `p` is essentially ambiguous though - I've had to use special flag to tweak handling it in libversion. So, as a last resort, `7.3.0.3+dfsg1`.

Upstream could be pinged too - they could'be just used patch component, without using to extra suffix.

**Comment by kkremitzki** [comment]
`+dfsg3` would indicate a third repacking of the upstream source to remove components that are not suitable per the Debian Free Software Guidelines, so it wouldn't make sense for that to be the version string for the first release of a new upstream version, and if I had picked 7.3.0.3 we would still be in this same situation. Yes, contacting upstream is probably the best way to get this ultimately resolved, but it won't be a solution in the short-term.

**Comment by AMDmi3** [comment]
> +dfsg3 would indicate a third repacking of the upstream

Sorry, dfsg was stray change. What I've meant is `7.3.0p3` → `7.3.0.p3`

> if I had picked 7.3.0.3 we would still be in this same situation

Repology can normalize that to `7.3.0p3` with a regexp, so it would be less of a problem. It would also not cause more problems if upstream releases e.g. `7.3.1`.

**Comment by kkremitzki** [comment]
> > +dfsg3 would indicate a third repacking of the upstream
> 
> Sorry, dfsg was stray change. What I've meant is `7.3.0p3` → `7.3.0.p3`
> 

Ah, yes, that would've worked as well.
