### ISSUE TITLE
sherlock: different projects

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#229]
https://repology.org/project/sherlock/versions
 - https://sherlock.inspiredcode.io/
 - https://sherlock-project.github.io/ (in Pentoo)

**Comment by AMDmi3** [comment]
Could you please add WWW for Pentoo ebuild so this can be split reliably?

**Comment by blshkv** [comment]
we keep the name of projects original, however I have moved to www-apps category and also updated metadata. Let me know if that's enough.

**Comment by AMDmi3** [comment]
See https://github.com/pentoo/pentoo-overlay/commit/0504fc73547cbf48073ce9dcdacdf2066527f97d#r34547607, but it's fixed
