### ISSUE TITLE
fonts:andika is too merged

### ISSUE THREAD

**Issue by awilfox** [repology/repology-rules#235]
`fonts:andika` includes Andika, a font with many glyphs which has current version 5.000.  There is also Andika New Basic, which has only basic Latin glyphs and has current version 5.500.

Repology is considering Debian's Andika New Basic package to be an Andika package.  This doesn't seem right because they are different typefaces and Andika has a much fuller set of glyphs (including non-Latin language support).

**Comment by sdht0** [comment]
@AMDmi3 the commit closed the wrong issue. I think you meant to close https://github.com/repology/repology-webapp/issues/235 in the other repo.

**Comment by AMDmi3** [comment]
Right, thanks for spotting. Let's fix this one too.
