### ISSUE TITLE
PyPI - Fedora missing packages

### ISSUE THREAD

**Issue by abitrolly** [repology/repology-rules#253]
I [found](https://github.com/repology/repology/issues/893#issuecomment-523852436) that there are Python packets on PyPI that are not linked to corresponding Fedora packages.

1. https://repology.org/project/python:datetime/versions

![image](https://user-images.githubusercontent.com/8781107/63512368-5641f580-c4ec-11e9-8751-240ddf0253fe.png)

https://apps.fedoraproject.org/packages/python-dateutil

2. https://pypi.org/project/straight.plugin/

There are two Repology entries for that package:
https://repology.org/project/python:straight.plugin/versions
https://repology.org/project/python:straight-plugin/versions

Fedora is only found in `python:straight-plugin` page, while the canonical name on PyPI is still `straight.plugin` which is used for lookup.

**Comment by AMDmi3** [comment]
Created rules for these. Note that the cause of this problem is Fedora (which doesn't use correct PyPI names) and partly upstream for using odd naming.

**Comment by abitrolly** [comment]
I got distracted and pasted page `python:datetime` instead of `python:dateutil`.

Why a rule is necessary for `python:straight.plugin`? PyPI uses it as a canonical name.

**Comment by AMDmi3** [comment]
> I got distracted and pasted page python:datetime instead of python:dateutil 

It's OK, I've figured it out.

> Why a rule is necessary for python:straight.plugin ? PyPI uses it as a canonical name.

The rule was necessary because Fedora uses `straight-plugin` instead of `straight.plugin`, to merge the former into the latter.

**Comment by abitrolly** [comment]
There is a way to detect PyPI name from `Provides: python3dist(CANONICAL_STANDARDIZED_NAME)` field.

https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_automatic_provides_with_a_standardized_name

`Provides:` is not used right now.

https://github.com/repology/repology/blob/613734c89c493bc5612d0e362c0019ad7f10984c/repology/parsers/parsers/repodata.py

Link to discussion.

https://discussion.fedoraproject.org/t/check-requirements-txt-against-existing-packages/2173?u=abitrolly

**Comment by AMDmi3** [comment]
There's nothing like that in Fedora repodata.

**Comment by abitrolly** [comment]
You mean that this information is only available in .rpm itself and not in repository indexes?
```
➜  ~ rpm -q --provides -p python3-straight-plugin-1.5.0-6.fc30.noarch.rpm 
python3-straight-plugin = 1.5.0-6.fc30
python3.7dist(straight.plugin) = 1.5.0
python3dist(straight.plugin) = 1.5.0
```
If that's the case then the only way it to find out if https://apps.fedoraproject.org/packages/python-straight-plugin/ parses .rpm to expose that metadata somehow.

**Comment by AMDmi3** [comment]
Well, Repology won't download and process individual RPMs anyway.

**Comment by abitrolly** [comment]
I left the wish here - https://github.com/fedora-infra/fedora-packages/issues/420#issuecomment-524527643

**Comment by abitrolly** [comment]
> There's nothing like that in Fedora repodata.

@AMDmi3 there is.
```
...
  <location href="Packages/p/python3-straight-plugin-1.5.0-5.fc29.noarch.rpm"/>
  <format>
    <rpm:license>BSD</rpm:license>
    <rpm:vendor>Fedora Project</rpm:vendor>
    <rpm:group>Unspecified</rpm:group>
    <rpm:buildhost>buildvm-ppc64le-07.ppc.fedoraproject.org</rpm:buildhost>
    <rpm:sourcerpm>python-straight-plugin-1.5.0-5.fc29.src.rpm</rpm:sourcerpm>
    <rpm:header-range start="4504" end="11400"/>
    <rpm:provides>
      <rpm:entry name="python3-straight-plugin" flags="EQ" epoch="0" ver="1.5.0" rel=
"5.fc29"/>
      <rpm:entry name="python3.7dist(straight.plugin)" flags="EQ" epoch="0" ver="1.5.
0"/>
      <rpm:entry name="python3dist(straight.plugin)" flags="EQ" epoch="0" ver="1.5.0"/>
    </rpm:provides>
    <rpm:requires>
      <rpm:entry name="python(abi)" flags="EQ" epoch="0" ver="3.7"/>
    </rpm:requires>
  </format>
...
```
https://github.com/repology/repology/blob/master/repology/parsers/parsers/repodata.py doesn't parse `rpm:provides`. Then I don't see where to store the link to PyPI.

**Comment by AMDmi3** [comment]
There is not.

```
wget -qO- https://mirror.yandex.ru/fedora/linux/releases/30/Everything/source/tree/repodata/e9c7a12f6bef422f16a609ec05552f770017a755a08a64edabf90774f2342d78-primary.xml.gz | gunzip | grep rpm:provides | wc -l
       0
```

**Comment by abitrolly** [comment]
There is some problem with your command line or mirror.
```
➜ curl -s https://mirror.datacenter.by/pub/fedoraproject.org/fedora/linux/releases/30/Everything/x86_64/os/repodata/54ed9948b74b314b877fa90468e7c5309a0f9428c35b938b82fa7b356a799c94-primary.xml.gz | gunzip | grep rpm:provides | wc -l
113394
```
![image](https://user-images.githubusercontent.com/8781107/63711274-b82f9180-c843-11e9-80da-bfa53309eeb0.png)

**Comment by AMDmi3** [comment]
> Everything/source
vs.
> Everything/x86_64
