### ISSUE TITLE
Moving absurd reponse to pkg-config/report here

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-rules#255]
I brought up a legitimate issue.  pkgconfig is misgrouped.  There are literally tens of thousands similar issues across all repositories.    Why are you discriminating against mine?

Please reconsider adding a rule that considers "pkgconfig" as "pkgconf".  The binary is called "pkg-config", so our name is as legitimate (or more so) than "pkgconf".

Please do the right thing here.  To tell me to change the name of a package used by hundreds of others is not right on your part.

**Comment by AMDmi3** [comment]
First, please submit meaningful issues. This one requires context you haven't referenced to have sense. Next, I've already stated: `pkgconf` and `pkg-config` are different projects - you can't fake on as another. There's another case like this, it's treated the same way.

**Comment by jrmarino** [comment]
You didn't state that.  You just said "rename it" callously.
And that's the point of the split/merge rules -- to group the packages to the same identifier.  There has to be hundreds of examples of packages with conflicting names.

The ravenports "pkgconfig" belongs to "pkgconf".  You've got a rule that says "pkgconf" == "pkg-config", and  that rule is too sweeping.  You need to make an exception for ravenports that pkgconfig => pkgconf here.  

Many packages are named after their primary binary, so RP calling this pkgconfig is perfectly reasonable and we shouldn't be penalized for that.

**Comment by AMDmi3** [comment]
Packages are named after the project packaged, and calling a package after unrelated project is not reasonable at all. What you call _penalization_ is just a natural result of incorrect data. Repology can afford adding rules to protect unrelated people from its effects, but definitely not to mask other's mistakes.

**Comment by jrmarino** [comment]
so I did *NOT* name it after a different project.  To imply that I did it intentionally just proves that you're being difficult just because you can.   It will take you a few seconds to fix this, but you're choosing to dig in and screw me, again.  I don't get your motivation.

And also: rude to call this a mistake.  Maybe you can say it could have had a better name 2 years ago when the project as young, but just because someone chooses something different doesn't automatically make it "a mistake".  That's just unadulterated arrogance.  If unintended, please try choosing more neutral words in the future.

**Comment by AMDmi3** [comment]
> did _NOT_ name it after a different project

Then it cannot mix up with different project and the issue is nonexistent.

> being difficult just because you can
> unadulterated arrogance

Sorry, I'm going to close reports in which you degrade to discussing my personality instead of technical issues right away from now on.
