### ISSUE TITLE
libffi version incorrect.

### ISSUE THREAD

**Issue by dylanaraps** [repology/repology-rules#257]
`3.2.1` is the latest upstream version, `replogy` lists `5.3.1`. OpenSUSE seems to bundle `libffi` with their GCC 5 and so it inherits the GCC version(?).

https://build.opensuse.org/package/show/openSUSE:Leap:42.3:Update/libffi-gcc5

**Comment by dylanaraps** [comment]
It looks to be caused by: https://github.com/repology/repology-rules/commit/4215b5c6d1d0070cca423d4e3e7f3b5b3d18833c

**Comment by dylanaraps** [comment]
Version is still incorrect.

See: https://build.opensuse.org/package/show/openSUSE:Leap:42.3:Update/libffi48

**Comment by AMDmi3** [comment]
Fixed
