### ISSUE TITLE
Firefox version incorrect.

### ISSUE THREAD

**Issue by dylanaraps** [repology/repology-rules#258]
`68.0.2` is the latest version yet FreeBSD ports lists `68.1.0` which doesn't exist. It also lists it for its ESR version (which affects regular Firefox on repology(?)).

https://www.freshports.org/www/firefox-esr

**Comment by AMDmi3** [comment]
It does exist, it's the official tarball from mozilla:

https://archive.mozilla.org/pub/firefox/candidates/68.1.0esr-candidates/build1/source/

> It also lists it for its ESR version (which affects regular Firefox on repology(?)).

Repology does not differentiate ESR version.

**Comment by dylanaraps** [comment]
That is a release candidate no? More of a beta than a stable release. I see also that Repology doesn't differentiate against beta versions of the non-ESR Firefox either. 

This wasn't the behavior I was expecting as Repology tracks development releases and "stable" releases separately.

From Repology: 

```
devel - newest known devel (or unstable) version. There may be both devel and newest versions for a given package.
```

**Comment by AMDmi3** [comment]
> That is a release candidate no? More of a beta than a stable release.

Judging by older releases, one of these 'candidates' is binary equivalent to the release (https://archive.mozilla.org/pub/firefox/candidates/68.0-candidates/build3/source/firefox-68.0.source.tar.xz == https://archive.mozilla.org/pub/firefox/releases/68.0/source/firefox-68.0.source.tar.xz), so this is almost a release which will be come official in a few days, and nothing like development or unstable version. I'd agree that packaging it is somewhat premature, but from Repology point of view it's beneficial to discover and report a new version as soon as possible.
