### ISSUE TITLE
Fix FreeBSD entries

### ISSUE THREAD

**Issue by luzpaz** [repology/repology-rules#264]
Trying to consolidate [freebsd entries](https://repology.org/projects/?search=freebsd&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=)
 
```yaml
# should capture names such as 'de-freebsd-doc'
# as well as 'zh-cn-freebsd-doc'
- { namepat: (?:..)(?:-..)?-freebsd-doc             setname: freebsd-docs }
- { name: freebsd-manpages                          name: freebsd-man-pages }
```

**Comment by AMDmi3** [comment]
I don't see much sense in it. All these are different FreeBSD parts packaged and versioned differently.
