### ISSUE TITLE
comparison of forks of packages

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#28]
there is at least one fork of openssl (openssl-1.0-chacha) which should be treated as an independent package:
https://repology.org/metapackage/openssl/versions
I have tried to request for a unique name (https://github.com/PeterMosmans/openssl/issues/51) but it has yet to be decided.

There is also a more complex example:
https://repology.org/metapackage/rtl8812au/versions
repology threats it as one package, however there are multiple forks of it:
rtl8812au https://github.com/abperiasamy/rtl8812AU_8821AU_linux
rtl8812au_astsam https://github.com/astsam/rtl8812au
rtl8812au_asus https://github.com/codeworkx/rtl8812au_asus/commits/master
rtl8812au_aircrack-ng https://github.com/aircrack-ng/rtl8812au

The last one is most active and provides patches for hacking which can't be merged back to the upstream. The official version is ```5.1.5~20180506``` (https://github.com/aircrack-ng/rtl8812au/commit/db3e2fa1738214037dc8dc2ccf3cc0a930ce1788) but it is not recognised correctely.

**Comment by AMDmi3** [comment]
> there is at least one fork of openssl (openssl-1.0-chacha) which should be treated as an independent package

I don't see it as an independent package. Technically it's a patchset to openssl which is not developed separately, tracks upstream and has the same versioning scheme.

> There is also a more complex example:

Probably something similar here, at least partially. It does not matter though as none of these seem to have official releases, so it should be marked as `noscheme`.

**Comment by blshkv** [comment]
I have added metadata.xml files for openssl (https://github.com/pentoo/pentoo-overlay/commit/32923c82e6af37066c43e282a0feaf46b1b062b9), not sure if it can help. Can exclude both ```PeterMosmans/openssl``` and ```drwetter/openssl-1.0.2.bad``` repositories or mark them properly?

Could you also mark rtl8812au as ```noscheme```?

These two flood the current outdated output (https://repology.org/metapackages/?inrepo=gentoo_ovl_pentoo&outdated=1) so it would be good to fix the issue

**Comment by blshkv** [comment]
Here you have it. The repology software is amazing and I use it every day. And I'm tired scrolling over the long list of all kind of versions in the history of openssl.

**Comment by AMDmi3** [comment]
Pentoo won't be updated until this crap is rolled back.

**Comment by blshkv** [comment]
ok, reverted. But can you help to come up with a temporary workaround? Such as ignoring these two forks in Pentoo perhaps?  openssl-* and rtl8812au_*.

It is a very long list to scroll on a mobile device.

**Comment by AMDmi3** [comment]
Thanks. You could've just reminded me that this issue requires action, will fix it now.

**Comment by AMDmi3** [comment]
Done. `openssl` case is quite interesting though, I have no idea how to deal with in properly yet. What's the purpose of `openssl-chacha` and `openssl-bad` in Pentoo?

**Comment by blshkv** [comment]
Both openssl cases are unusual indeed and required by tools for old protocol/cipher validations (SSLv2 etc). openssl-bad is still required by https://testssl.sh. The second one, openssl-chacha (https://github.com/PeterMosmans/openssl) used to be required by sslyze but this is no longer the case as I just realized. I can remove it.

**Comment by AMDmi3** [comment]
Thought so. Well, `openssl-bad` was not merged anyway.

The correct thing would be to merge it though, as it's still `openssl` (and from practical standpoint, for example, when we support vulnerabilities, openssl vulns should be reported for this too). The problem however is that from one hand, it's not probably going to be updated, from the other - it may be needed for some important package and it's expected for repositories to not want outdated entries reported which cannot be updated.

Would be most correct to merge it and mark as `legacy`, however I don't want to bother now. Seems like all your problematic packages were fixed?

**Comment by blshkv** [comment]
yes, it's all fixed for now. let's close it finally. Thanks!
