### ISSUE TITLE
argparse: different reposotories

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#280]
https://pypi.org/project/argparse/
https://github.com/ThomasWaldmann/argparse/

and:
https://github.com/Microsoft/vcpkg/tree/master/ports/argparse
https://github.com/p-ranav/argparse

**Comment by AMDmi3** [comment]
Sorry, I have no idea what this is supposed to mean.

**Comment by blshkv** [comment]
yeah, sorry I was lazy.
Have a look at https://repology.org/project/python:argparse/versions


Vcpkg shows an update, but it belongs to a different package (p-ranav/argparse)
