### ISSUE TITLE
gnupg1 and gnupg2 shouldn't be merged.

### ISSUE THREAD

**Issue by dylanaraps** [repology/repology-rules#285]
I think it's wrong to display `gnupg1` as an outdated version of `gnupg2`. They're separate tools with different target audiences and different purposes. 

- GnuPG 1 (classic) is separate and intended for embedded and server usage, it brings in less dependencies and is far smaller in size.

- GnuPG 2 is separate and intended for desktop usage, it brings in a handful of additional dependencies and is larger in size.

Both of these tools can be installed at the same time.

---

> This is the standalone version of gpg. For desktop use you should consider using gpg2 from the GnuPG-2 package (On some platforms gpg2 is installed under the name gpg)

Source: From the GnuPG 1.4 man page.

> In contrast to the standalone version gpg, which is more suited for server and embedded platforms, this version is commonly installed under the name gpg2 and more targeted to the desktop as it requires several other modules to be installed.

Source: From the GnuPG 2 man page.

> [...] allows co-existence of older GnuPG versions with GnuPG 2.1. However, any change to the private keys using the new gpg will not show up when using pre-2.1 versions of GnuPG and vice versa.

Source: GnuPG 2.1 changelog.

> Kind of: 1.4 will be kept alive for use with PGP 2 encrypted and
signated data and maybe for old platforms.  However, modern algorithms
won't be added to 1.4.

Source: https://lists.gnupg.org/pipermail/gnupg-users/2018-January/059815.html

| Package | Ver. | End-of-life | Birth |
|-----------|-----|--------------|-------|
| GnuPG   | 1.0  | 2002-09-07  | 1999-09-07 |
|         | 1.2  | 2005-01-01  | 2002-09-21 |
| SEE        | **1.4**  | **none (1)**    | 2004-12-16 |
|         | 2.0  | 2017-12-31  | 2006-11-11 |
|         | 2.2  | tba 	       | 2014-11-06 |

> GnuPG 1.4 is the old, single binary version which still support the unsafe PGP-2 keys. This branch has no dependencies on the above listed libraries or the Pinentry. However, it lacks many modern features and will receive only important updates. 

GnuPG 1 has no EOL date.

Source: https://gnupg.org/download/index.html

**Comment by AMDmi3** [comment]
The important thing is that they are the same project, besides it explicitly says that gpg1 is legacy not supporting modern cryptography.
Merging different branches of the same project should not have any drawbacks - with recent changes it works as follows:
- if a repository has both gpg2 and gpg1 of latest versions, these are classified as latest/legacy correspondingly, which IMO reflects the upstream status very well 
- both versions may be outdated independently if there's corresponding greater 2.x or 1.x version in another repository
- in absence of gpg2, gpg1 would be classified as outdated because the latest version is missing

**Comment by dylanaraps** [comment]
> The important thing is that they are the same project, besides it explicitly says that gpg1 is legacy not supporting modern cryptography.

They may be the same project but they've diverged so much that I'd call classify them as different pieces of software entirely. `gnupg1` is also still maintained and suitable for use. 

> "GnuPG-2 has a different architecture than GnuPG-1 (e.g. 1.4.7) in that
it splits up functionality into several modules. However, both
versions may be installed alongside without any conflict. In fact,
the gpg version from GnuPG-1 is able to make use of the gpg-agent as
included in GnuPG-2 and allows for seamless passphrase caching. The
advantage of GnuPG-1 is its smaller size and the lack of dependency on
other modules at run and build time. We will keep maintaining GnuPG-1
versions because they are very useful for small systems and for server
based applications requiring only OpenPGP support." 

Source: https://lists.gnupg.org/pipermail/gnupg-announce/2007q2/000254.html

> in absence of gpg2, gpg1 would be classified as outdated because the latest version is missing

This is the behavior I disagree with.

I think it makes much more sense to to keep the split. KISS' `gnupg1` package is flagged as out of date despite it being the latest version of `gnupg1` which is misleading.

There are specific reasons for packaging one or the other. KISS includes only `gnupg1` in its core repositories as it requires no additional dependencies and is smaller in size (*the intention is to use it for signed repositories, see: https://github.com/kisslinux/kiss/issues/60*).

**Comment by AMDmi3** [comment]
I've seen no justification of why gnupg1 should be a different project - it's the same as legacy branch of any other software - less resource requirements and dependencies with less features and no development.
The real reason for this issue seem to be that you don't want to provide gnupg2, but you need to use gnupg1. Strictly speaking, you cannot control how your users use gpg, and some may need what you call "desktop" features, and for these you provide an outdated version. So I consider Repology behavior legit in this case.

**Comment by dylanaraps** [comment]
> it's the same as legacy branch of any other software

It should then be marked as a legacy version on repology and not an out-of-date version no? 

> The real reason for this issue seem to be that you don't want to provide gnupg2, but you need to use gnupg1. 

`gnupg2` will be packaged in `community` if and when a user wants to package it. `gnupg2` will just be absent from the `core` repositories. Even if `gnupg2` were packaged in `community`, the `core` repositories would still show `gnupg1` as out-of-date (*on Repology*).

> what you call "desktop" features

This is exactly how the `gnupg` developers describe `gnupg2`. See my above comments.

> Strictly speaking, you cannot control how your users use gpg, and some may need what you call "desktop" features, and for these you provide an outdated version.

Of course, however we're talking about a package in the `core` repositories and not the restriction of user choice. This is totally irrelevant to the current discussion.

KISS as a distribution has a minimal set of core repositories and this is intentional. `gnupg1` is used as it requires zero additional dependencies and is small in size. One of the system types `gnupg1` is intended for, *is* KISS (*small systems*) .  

Nothing stops a user from adding `gnupg2` to `community` or packaging `gnupg2` in their own local repository themselves. These are the supported methods of adding additional software to KISS. User repositories can also be shared and function no differently to `community` does.

> So I consider Repology behavior legit in this case.

My issue stems from `gnupg1` **not** being an outdated version of `gnupg2` but a separate piece of software entirely (*even if it can be called "legacy"*). 

- `gnupg1` has a different intended usage (*embedded systems, servers and **small systems***).
- `gnupg1` can be installed alongside `gnupg2` without a single conflict.
- `gnupg2` has diverged so much from `gnupg1` in design and implementation ,that it *is* something different entirely

Repology reporting `gnupg1` as being outdated in KISS' repositories is misleading and false. Our `gnupg1` *is* the latest version of *`gnupg1`* and it's incorrect to call `gnupg1` an outdated version of `gnupg2`. They're separate pieces of software with different use-cases and target audiences.

`gnupg1` is a perfect fit for KISS' `core` as it's small and requires no additional dependencies. One of `gnupg1`'s intended audiences *is* KISS (*small systems*). 

I'd very much appreciate it if we could keep this civil and on topic. I really love Repology and it aids me daily with development of KISS. Thank you for providing it, free and open source. :+1:

**Comment by AMDmi3** [comment]
Okay, let's split it back for now. Note that this is not final, but I need some time to decide on how to handle this case properly - there are at least two factors here, namely the specific need for a older version (other similar cases are `sdl` and `gtk`) and a presence of community repository (other similar case is `arch`/`aur`) which may contain the latest version. I don't have clear decision on how to handle either of these, not speaking of their mixture.

Other possible solutions would be to leave it be (it **is** outdated, and repology correctly reports it - you don't need to be too concerned about it if you feel that you don't need to do anything about it), or to silence it by forcing gnupg in kiss core to legacy status.
