### ISSUE TITLE
xconq-7.5.0-0pre.0.20050612

### ISSUE THREAD

**Issue by davidak** [repology/repology-rules#298]
`xconq: WARNING: possibly ambiguous package name "xconq-7.5.0-0pre.0.20050612", consider adding explicit version`

Source: https://repology.org/log/1585935

That is actually the official latest version: https://sourceforge.net/projects/xconq/files/xconq/xconq-7.5.0-0pre.0.20050612/

7.5.0 was never released.

https://repology.org/project/xconq/versions

nixpkgs should get marked as up to date and Rosa / RPM Sphere version should be fixed. The data might be there: https://abf.io/import/xconq/blob/rosa2016.1/xconq.spec

**Comment by AMDmi3** [comment]
Note that this has nothing to do with the cited log.
