### ISSUE TITLE
ccgfs: version considered older but isn't

### ISSUE THREAD

**Issue by jengelh** [repology/repology-rules#312]
== Observed behavior ==
https://repology.org/project/ccgfs/versions shows:
openSUSE Leap 15.2, version 0.81 in blue
openSUSE Tumbleweed, version 0.81.g3 in red.

== Expected behavior ==
Show 0.81.g3 in green, because this is actually a higher version according to the standard RPM version compare.

**Comment by AMDmi3** [comment]
`0.81.g3` is fake, so you are not to expect any specific behavior regarding it. In practice, it would be either marked incorrect or outdated.

**Comment by jengelh** [comment]
Well, it is used to indicate a newer-than-0.81 snapshot of the git tree (3 commits ahead). Is there a different syntax that repology recognizes?

**Comment by AMDmi3** [comment]
I've given a link. There's no ready to use solution, but I'm open to discussion.
