### ISSUE TITLE
Missing normalization for rust (sniffglue)

### ISSUE THREAD

**Issue by kpcyrd** [repology/repology-rules#315]
I'm the author of sniffglue and noticed the package status is split into two pages:

https://repology.org/project/rust:sniffglue/versions
https://repology.org/project/sniffglue/versions

I'm not familiar how to fix this but having them merged would be awesome. :)

**Comment by kpcyrd** [comment]
Is there a way to solve this for all of them at once or should I submit PRs for all my projects affected by this?

**Comment by AMDmi3** [comment]
There's no way, so you should.
