### ISSUE TITLE
freshcode.club reporting incorrect version for CMake

### ISSUE THREAD

**Issue by luzpaz** [repology/repology-rules#318]
Any idea why?

On https://freshcode.club/projects/cmake it report 3.16.2
but on repology:  
[![freshcode.club entry](https://repology.org/badge/version-for-repo/freshcode/cmake.svg)](https://repology.org/project/cmake/versions)

[![Packaging status](https://repology.org/badge/vertical-allrepos/cmake.svg)](https://repology.org/project/cmake/versions)

**Comment by AMDmi3** [comment]
No idea, what their feed contains that Repology shows.
