### ISSUE TITLE
yara: strange name in Scoop

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#325]
https://repology.org/project/yara/versions

Scoop came up with "3.11.0-994" name and it is not clear where it came from.

**Comment by AMDmi3** [comment]
https://github.com/ScoopInstaller/Main/blob/17d3a7b8e0f9a0625b6002fee3d844ff660094bf/bucket/yara.json#L8

**Comment by blshkv** [comment]
Thanks!
