### ISSUE TITLE
Correct method of specifying that a version pill git latest?

### ISSUE THREAD

**Issue by dylanaraps** [repology/repology-rules#326]
KISS' vim package was updated to follow the latest git commit and the version was changed to `git`. Repology still shows this as being an outdated package.

**Comment by AMDmi3** [comment]
If the `git` version reliably indicates rolling version in KISS, can add rule to treat it as rolling.

**Comment by dylanaraps** [comment]
Yes, `git` is the identifier for a rolling version of a package. Thanks.
