### ISSUE TITLE
Please blacklist 'ALT Linux p9', 'ALT Sisyphus', 'Mageia', 'Rosa' as latest version source because they make up package versions

### ISSUE THREAD

**Issue by yurivict** [repology/repology-rules#327]
Case: ```poly2tri``` package https://repology.org/project/poly2tri/versions

They all list https://github.com/jhasse/poly2tri as the upstream URL, but that project didn't have any releases. They made up ```1.0``` as a release number.

Because of this reason repology queries would always show that everybody else is behind, when in reality their version is fake.

**Comment by AMDmi3** [comment]
This has nothing to do with alt, mageia and rosa.
