### ISSUE TITLE
extra-cmake-modules version incorrect.

### ISSUE THREAD

**Issue by dylanaraps** [repology/repology-rules#334]
The newest release (5.67.0) is an `-rc` release and not a full/final release.

See: 

- https://github.com/KDE/extra-cmake-modules/releases
- https://repology.org/projects/?inrepo=kiss_main&outdated=1
- https://repology.org/project/extra-cmake-modules/versions

**Comment by AMDmi3** [comment]
Releases reliably come within a week from rc's, so I do not consider this a problem.

**Comment by AMDmi3** [comment]
Otoh, we're now tracking release times, and such behavior would make them unreliable, so ignoring versions which look like KDE releases from kaos build proactively.
