### ISSUE TITLE
ffmpeg version incorrect.

### ISSUE THREAD

**Issue by dylanaraps** [repology/repology-rules#336]
Latest version is `4.2.2` as can be seen here: https://ffmpeg.org/download.html#releases

The incorrect version is from an AUR package which downloads a specific git hash and calls itself version `4.2.3`. https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ffmpeg-libfdk_aac

The commit in the above AUR packages points to the `4.2.2` release commit. https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/192d1d34eb3668fa27f433e96036340e1e5077a0

**Comment by AMDmi3** [comment]
For the note, this was fixed in AUR (https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=ffmpeg-libfdk_aac&id=8e2a1d9ba4951816ac83eedcf985dafc90f9cb97)
