### ISSUE TITLE
intel-media-driver version incorrect.

### ISSUE THREAD

**Issue by dylanaraps** [repology/repology-rules#350]
FreeBSD's version is really the latest pre-release. https://github.com/intel/media-driver/releases

https://repology.org/project/intel-media-driver/versions

**Comment by dylanaraps** [comment]
The version is still incorrect. Repology still lists a devel pre-release from FreeBSD. :+1:

**Comment by AMDmi3** [comment]
No, it's correct 20.1.0r release version.
