### ISSUE TITLE
*-dbg duplicates in Adélie Linux

### ISSUE THREAD

**Issue by mikhailnov** [repology/repology-rules#351]
https://repology.org/project/telegram-desktop/versions
Here 'telegram' and 'telegram-dbg' are displayed seperately, but it is the same package

**Comment by AMDmi3** [comment]
They are different packages originating from a single APKBUILD.

**Comment by mikhailnov** [comment]
That is odd... why don't you display debuginfo.rpm for example?

**Comment by AMDmi3** [comment]
I "display" what repositories report.

**Comment by mikhailnov** [comment]
That depends from which repositories you parse. For example, you do not parse http://abf-downloads.rosalinux.ru/rosa2019.1/repository/x86_64/debug_main/release/ and do not display for example `FaxMail-debuginfo`, because you parse SRPMs (if I am not mistaken) in a smart way and because RPM produce debuginfo subpackages automatically without defining them in the spec file.
If Adélie Linux does not make a separate repository of *-deb packages, it is just their approach to how to ship debuginfo. Arch Linux which also uses PKGBUILDs does not ship debuginfo at all.
That is why, to my mind, these packages look like odd information which overloads the Repology website.

**Comment by AMDmi3** [comment]
The target is to parse all available sources for each repository (e.g. binary packages in addition to source, as long as they provide enough information to correctly match them to the projects) and teach the site to display a lot of similar entries in a more compact form. Before that I don't care of this much.
