### ISSUE TITLE
Display outdated packages by more than 1 version

### ISSUE THREAD

**Issue by mustaqimM** [repology/repology-rules#352]
I would like the option for the search to return packages that are outdated/newer by more than 1 version.

**Comment by AMDmi3** [comment]
What's the use case?

**Comment by mustaqimM** [comment]
I wish to first update packages for a distro that are a couple of versions behind. In Void Linux the users need to take the initiative to keep packages up to date and sometimes popular packages are neglected.

Just recently I found docker being kept up to date, but containerd, on which it relies was lagging behind.

**Comment by AMDmi3** [comment]
I don't see much sense in this. Difference between version numbers has no semantic meaning and is not even always possible to calculate. Any non-latest version equally needs an update.
