### ISSUE TITLE
libelf versioning

### ISSUE THREAD

**Issue by dylanaraps** [repology/repology-rules#374]
There are 3(?) implementations of `libelf` for Linux (and most likely other operating systems). KISS
just swapped to the `elftoolchain` version of `libelf` and the version number was adjusted accordingly.

- elftoolchain: `libelf 0.7.1` (KISS now uses this one)
- elfutils: `libelf 0.179`
- libelf (which repology lists): `libelf 0.8.13`

KISS swapped to the `elftoolchain` version for a few reasons:

1. `libelf` (0.8.13 provider) hasn't seen development in years.
2. Newer Linux kernel versions will no longer work with old `libelf`.
3. `elfutils` is very cumbersome to package as it depends heavily on `glibc`.

The reason I'm opening this issue is that Repology is listing our new `libelf` as being an outdated version of the old `libelf`.

**Comment by AMDmi3** [comment]
So you're distributing `elftoolchain`, but naming it with a different projects name `libelf`. I think that is the cause of the problem.

**Comment by dylanaraps** [comment]
I'm only distributing `libelf` **from** `elftoolchain` (just this single library). This is exactly how `libuuid`, `libblkid` etc are packaged by other distributions. They're split away from the provider (util-linux, e2fsprogs or etc).

**Comment by dylanaraps** [comment]
There's also already a similar rule for Arch's `libelf` package (which is from the `elfutils` project). 

https://github.com/repology/repology-rules/blob/fa4178f8ae7e0ea0bacbfebd3438833e77e97238/850.split-ambiguities/l.yaml#L23
