### ISSUE TITLE
Adacore versioning

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-rules#376]
Here's a list of sources for Adacore's annual community rereleases:
```
aunit-2020-20200429-19B6C-src.tar.gz
aws-2020-20200429-19A9F-src.tar.gz
gnat-2020-20200429-19B04-src.tar.gz
gnatcoll-bindings-20.0-20191009-1B2EA-src.tar.gz
gnatcoll-core-20.0-20191009-1B40E-src.tar.gz
gnatcoll-core-2020-20200429-19B7C-src.tar.gz
gnatmem-2020-20200429-19911-src.tar.gz
gnatsymbolize-2020-20200429-19987-src.tar.gz
gprbuild-2020-20200429-19BD2-src.tar.gz
langkit-20.0-20191009-1B1A1-src.tar.gz
langkit-2020-20200429-19994-src.tar.gz
libadalang-20.0-20191009-1B2D7-src.tar.gz
libadalang-2020-20200429-19982-src.tar.gz
libadalang-tools-20.0-20191009-1B002-src.tar.gz
libadalang-tools-2020-20200429-1998C-src.tar.gz
spark-2020-2020-20200429-19AA5-src.tar.gz
xmlada-2020-20200429-19A99-src.tar.gz
gtkada-2020-20200429-19B96-src.tar.gz
```
What should stand out:

1.  Most follow the pattern 2020-20200429-XXXXX as the name.
2. Some have multiple versions (e.g. langkit, gnatcoll-core, etc)
3. A few have a 2019 date with "20.0" main version.

Taking gnatcoll-bindings as an example.
For me gnatcoll-bindings-20.0-20191009-1B2EA is equivalent to taking the 2019 release and add some patches.  I would have versioned this as 2019 with a revision.  But gentoo is ignoring the file name scheme that has been clearly established for the true 2020 releases and just calling it "2020".  So if I update this to 2019, it's going to show as obsolete even though it is the same version.

It's been established that the filename means something wrt to versions.  There's been lots of problem reports denied based on naming.  

I know this is not a simple issue, but going with previous rulings, gentoo is using a fake version by calling it 2020 when it's clearly labeled "20.0" with a 2019 date.  Note that on github, adacore tags with both "20.0" and "2018", "2019", "2020" and gnatcoll-bindings has been released as "2019" last year, so clearly they are distinct tags and should not be conflated.

So I need a ruling here.
Are you going to force all other repositories to use the same fake name as gentoo, or otherwise their version shown (incorrectly) as obsolete for an entire year?  
And is this setting a new precedent?  Because you've been very clear on other version rulings and I believe this one violates those previous ones.  So there's got to be some consistency here, right?

**Comment by AMDmi3** [comment]
> Here's a list of sources for Adacore's annual community rereleases:

You've forgot to mention that it's a list of sources for **2020** release.

> For me gnatcoll-bindings-20.0-20191009-1B2EA is equivalent to taking the 2019 release

Which just contradicts to the above mentioned fact. `gnatcoll-bindings-2019-20190430-1928C-src.tar.gz` corresponds to 2019, `gnatcoll-bindings-20.0-20191009-1B2EA-src.tar.gz` corresponds to 2020, so as long as "annual releases" are used for versioning these, gentoo's 2020 is absolutely correct, and in no case 2019 would be correct for `gnatcoll-bindings-20.0-20191009-1B2EA-src.tar.gz`. If someone used 20.0 or 20191009 I'd just mark this as noscheme.

**Comment by jrmarino** [comment]
okay so I mentioned this case from the list above:
```
gnatcoll-core-20.0-20191009-1B40E-src.tar.gz
gnatcoll-core-2020-20200429-19B7C-src.tar.gz
```
That means both tarballs were used to build adacore product.  If somebody was to use exactly the same approach, they would need to package BOTH of them.
How would they be named properly for repology?

And what happens if Adacore tags their upstream github repo for gnatcore-bindings with a 2020 tag say on a recent comment that's roughly 6 months older the Oct 2019?  If I package that tag as 2020, then I'm 100% correct based on previous rulings.  But now we have two sources for 2020.  This source tarball and upstream.  How are you as Repology judge going to rule in that case?

and FYI, AdaCore does back tag upon request.  They've done it recently and I may ask them to tag some of these like gnatcoll-binding so this case is not hypothetical.

**Comment by AMDmi3** [comment]
> How would they be named properly for repology?

They shouldn't be named "for repology". I don't care how they are packaged as long as they use compatible versioning schemes, and currently they all use YYYY scheme, which is unambiguous, disregarding your speculation that the year is taken from the date and e.g. gnatcoll-bindings for 2020 should be 2019.

> And what happens if Adacore tags ...  But now we have two sources for 2020

Repology won't break on multiple 2020 versions and neither of them is outdated.

**Comment by jrmarino** [comment]
I'm not following.
again, given
```
gnatcoll-core-20.0-20191009-1B40E-src.tar.gz
gnatcoll-core-2020-20200429-19B7C-src.tar.gz
```
You're saying they are both "2020" since they are listed in the source files.  Both tarballs exist.  So both would be correctly identified as "2020" by your logic.  I think we can both agree that one tarball is newer than the other, thus calling them both "2020" doesn't make sense.

You didn't answer my question above though.  What happens if/when the upstream repository is tagged 2020?  I'm trying to show how saying it's 2020 because it's group together can fall apart and again it's not hypothetical.

I'm trying to do the right thing here.
I don't think gentoo has done the right thing.
However, since you believe they did, Ravenports and every other repositiory has to follow suite on gentoo, right?  Like it or not, Repology *is* driving naming schemes.  I actually thought this was one of your original goals -- to bring all repositories to a more common foundation.  I think you've generally succeeded in this.  But that means your decisions influence this, and thus "naming for repology" is a thing.  Because I don't want my interpretation of the proper name to be marked as incorrect for 1 or more years.  So I either follow gentoo against what I think is correct or make a stand for correctness and have an up-to-date repository marked out-of-date.

**Comment by AMDmi3** [comment]
Don't not ask me how to "do no the right thing" - do whatever is more suitable from the point of packaging. From my side, if that doesn't conflict with other repos I don't care, if it does I can mark your version ignored, or mark other versions ignored, or mark some versions as alternate schemes so they can coexist, or mark the whole thing as noscheme, depending on circumstances. I'm not wasting any time on this unless there's a conflict.

**Comment by jrmarino** [comment]
Well, I am asking because Adacore is a special case and this kind of thing has been going on for more than a decade.  They are getting better but there's always going to be issues like this.

If you ask them about the 2020 release of gnatcoll-bindings, they would likely say there is no 2020 release.  I know this because I've dealt with them for years.  So I was more or less asking to come up with an approach for Adacore due to their dual scheme, etc.  

So what's clear is that I've got to call the next update "2020".  If adacore in the future identifies a true 2020 release, I'll also call that "2020" but just bump the revision.  Gentoo will not see that because the version won't change.  But  I won't care because they caused the mess to begin with.

**Comment by AMDmi3** [comment]
> If you ask them about the 2020 release of gnatcoll-bindings, they would likely say there is no 2020 release. I know this because I've dealt with them for years. So I was more or less asking to come up with an approach for Adacore due to their dual scheme, etc.

Unfortunately, there's nothing sane which can be done if upstream does not use sane versioning scheme. Garbage in - garbage out. We have noscheme exactly for cases like that, but here, as long as everybody still uses compatible scheme, leaving it be would bring more benefit, as it still allows reporting 201x versions as outdated.

> So what's clear is that I've got to call the next update "2020". If adacore in the future identifies a true 2020 release, I'll also call that "2020" but just bump the revision. Gentoo will not see that because the version won't change. But I won't care because they caused the mess to begin with.

This sounds fair. Some update information would be lost, but no false positives would be generated.

**Comment by jrmarino** [comment]
ok
