### ISSUE TITLE
killerbee: must be x.y.z version format

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#38]
https://repology.org/metapackage/killerbee/versions

Somehow, 99 was choosen as the highest version, however the tool uses a different scheme.
See https://github.com/riverloopsec/killerbee/blob/master/setup.py#L78

The autor will be releasing 2.7.x accodring to the following:
https://github.com/riverloopsec/killerbee/issues/128

**Comment by blshkv** [comment]
Hmm.. Somehow, 99 is still chosen as the latest stable version, but it is a "live" package, similar to 9999 in pentoo

**Comment by AMDmi3** [comment]
It takes time to update.
