### ISSUE TITLE
Some Termux packages are not being picked up

### ISSUE THREAD

**Issue by buttaface** [repology/repology-rules#382]
The [libdispatch](https://bintray.com/termux/termux-packages-24/libdispatch) and [ecj](https://bintray.com/termux/termux-packages-24/ecj) packages [are not](https://repology.org/project/libdispatch/versions) [picked up](https://repology.org/project/ecj/versions) for some reason. I thought it might be because the version numbers are prefixed with `1:`,  but others [like ltrace do that too](https://github.com/termux/termux-packages/blob/master/packages/ltrace/build.sh#L4) and are [still picked up](https://repology.org/project/ltrace/versions). Don't know what's going on, maybe there's a debug log that you generate that can clear things up.

Looking into it further, probably related to the fact that those packages have [the prefix before a bash variable](https://github.com/termux/termux-packages/blob/master/packages/ecj/build.sh#L7)?

**Comment by AMDmi3** [comment]
There are no such packages in https://dl.bintray.com/termux/metadata/repology/packages.json
@fornwall

**Comment by buttaface** [comment]
OK, [found the reason why they're not in the list you linked](https://github.com/termux/termux-packages/blob/master/scripts/repology/excluded_packages.txt), I didn't know that the Termux package repo was submitting a list to you. I figured you were scraping the repo instead, I'll look into that over there instead then.

**Comment by AMDmi3** [comment]
Oh my god. I'm not going to tolerate faking repository information.

@xeffyr
Please stop modifying package lists for Repology at once. Rules can be added for most of these instaed.

**Comment by AMDmi3** [comment]
Fixed upstream.
