### ISSUE TITLE
Detecting libreoffice development versions

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-rules#384]
> well, in any case, 6.4.5.x is still a development version. But you said you were expecting a pull request. The problem is the last time the rule masked when the actual release came out for months, so I'm wondering if there's a better way to identify development releases. LO is showing a false version as a release right now, and has for at least 10 days. So something needs to be tweaked -- the question is how...

So what's the best way to identify LO devel versions by rule rather than manually setting them which leads to authentic releases getting masked indefinitely (until someone notices) when the devel version becomes the basis for release?
Is there anyway to identify these versions as a recognizable pattern?

**Comment by AMDmi3** [comment]
I have no idea. You should probably ask LO devs first.

**Comment by jrmarino** [comment]
So for libreoffice, a current beta (7.0.0) is now showing as latest.  It has source url of this on AUR:
https://dev-builds.libreoffice.org/pre-releases/rpm/x86_64/${_pkgnamefmt}_${_LOver}_Linux_x86-64_rpm.tar.gz"

So could there be a rule to consider url prefix of "https://dev-builds.libreoffice.org/pre-releases" as devel versions?

**Comment by AMDmi3** [comment]
No, the latest is 7.0.0.1 and it's neither beta nor dev-build. http://downloadarchive.documentfoundation.org/libreoffice/old/7.0.0.1/src/

**Comment by AMDmi3** [comment]
For the record, the very 6.4.5 this report had started from is now _listed_ as the official latest version on https://www.libreoffice.org/download/download/, which indicates that it's just the website lagging and this is a non-issue. I'll just see how it goes with 7.0.0

**Comment by jrmarino** [comment]
As of this writing, 7.0.0 is listed on the official site as a pre-release on that exact link:
https://www.libreoffice.org/download/download/
Yes, I know 6.4.5 has now been released.
But it was in the same case that 7.0.0.x is in now.  The pre-release url rule would have worked for AUR, but I'm not sure what to do with the link you made 2 posts up.  7.0.0.1 is not clearly a pre-release from that url.

**Comment by AMDmi3** [comment]
> Yes, I know 6.4.5 has now been released.

No, it had been released before the issue was reported. The release hasn't changed at all, just the page was updated with some lag, so I'm not going to consider the page at all.

I'm going to add a rule which treats A.B.C.1 as devel - I haven't seen any documentation on this, but the pattern where there's always A.B.C.2 which is then announced as official release is obvious.

**Comment by jrmarino** [comment]
Okay.  That may be good enough.  I'll reopen if something changes.
