### ISSUE TITLE
Future version of Clementine marked as stable

### ISSUE THREAD

**Issue by mimi89999** [repology/repology-rules#387]
Hello,
I noticed that the repology marked 1.4.0 as stable (https://repology.org/project/clementine-player/information). However both the website (https://www.clementine-player.org/) and GitHub tags have 1.3.1 as latest stable (https://github.com/clementine-player/Clementine/releases/latest)

**Comment by mimi89999** [comment]
BTW, why aren't you checking GitHub releases (they have an API for that) or parsing project websites as `just-install` is doing to discover new versions (https://github.com/just-install/just-install-updater-go/blob/master/jiup/rules/rules.go)?

**Comment by AMDmi3** [comment]
GitHub parsing is not implemented yet (repology/repology-updater#938, repology/repology-updater#1). Parsing project websites will unlikely be implemented.

**Comment by mimi89999** [comment]
Now `1.3.93` from KaOS is marked as latest. Before it, there is `1.3.92` from OpenSuse
