### ISSUE TITLE
Preview version of mono marked as stable

### ISSUE THREAD

**Issue by mimi89999** [repology/repology-rules#388]
Hello,
`mono` version `6.10.0.104` listed in the `crux` repo is marked as stable, but it is a preview version. Current stable is still `6.8.0.123` (https://www.mono-project.com/download/stable/).

**Comment by AMDmi3** [comment]
Since there's no way to know whether a version is preview based on a version solely, I'm expecting pull requests if you're willing to keep a devel rule for it up to date. Related to #384.

**Comment by mimi89999** [comment]
Hmm... `just-install` is parsing the website. Maybe the same could be implemented in repology or you could trust the version in `just-install` to be stable.

**Comment by AMDmi3** [comment]
No, Repology won't parse websites because it's either unreliable and or it requires a lot of handwork and is still unreliable.
And no, Repology won't trust just-install, as it contains incorrect versions just like any other repo: https://repology.org/projects/?inrepo=just-install&problematic=1
