### ISSUE TITLE
gcc devel versions from 5 on

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-rules#392]
Since GCC 5, the release versions are defined as "x.y.0" where "x" is major version and y is minor version.  (The first minor component of a major release always starts with "1").

I believe if the second component (y) is "0", or the third component is anything other than "0", then it's a development version.   Right now there are several examples of "x.y.1" in repology (e.g. 9.3.1).  These are snapshots.
example:
http://mirror.koddos.net/gcc/releases/gcc-9.3.0/

```
[   ]	gcc-9.3.0.tar.gz	2020-03-12 12:29	118M	 
[   ]	gcc-9.3.0.tar.gz.sig	2020-03-12 12:32	72	 
[   ]	gcc-9.3.0.tar.xz	2020-03-12 12:28	67M	 
[   ]	gcc-9.3.0.tar.xz.sig	2020-03-12 12:32	72	 
[   ]	sha512.sum	2020-03-12 12:44	596	 
```
(there is no 9.3.1 directory because that version is not a release)

something like:
http://mirror.koddos.net/gcc/snapshots/9-20200710/ has:

```
gcc-9-20200710.tar.xz	Complete GCC
```

When built, gcc version would be presented as 9.3.1

Can the existing gcc devel rules be modified to consider given (x.y.z) that y = 0 or z /= 0 be a snapshot and not a release?

**Comment by AMDmi3** [comment]
Please check rules before submitting issues. This is already implemented.
