### ISSUE TITLE
Xfce 4.15 shows as stable but it's pre-release version

### ISSUE THREAD

**Issue by protonesso** [repology/repology-rules#406]
Hi, most xfce4 packages (xfwm4, xfsesktop, thunar, xfce4-session and every single package listed here: https://archive.xfce.org/src/xfce/) using odd numbers to identify development releases like gnome does.

**Comment by AMDmi3** [comment]
Done, except for thunar-volman and tumbler which used odd minor versions either in [xfce 4.14](https://archive.xfce.org/xfce/4.14/src/) or [xfce 4.12](https://archive.xfce.org/xfce/4.12/src/]
