### ISSUE TITLE
Scheme packages

### ISSUE THREAD

**Issue by lassik** [repology/repology-rules#411]
All current `chibi` packages:

* `mageia_6`
* `mageia_7`
* `mageia_cauldron`
* `altsisyphus`
* `alt_p9`

are the same package as `chibi-scheme`. Since the latter is a more popular name, should `chibi` be merged into it?

**Comment by lassik** [comment]
`sagittarius` in `aur` is the same package as `sagittarius-scheme` in all other repos.

**Comment by lassik** [comment]
These `gerbil` packages are the same as `gerbil-scheme`:

```json
{
  "repo": "gnuguix",
  "name": "gerbil",
  "summary": "Meta-dialect of Scheme with post-modern features"
}
{
  "repo": "nix_stable",
  "name": "gerbil",
  "summary": "Gerbil Scheme"
}
{
  "repo": "nix_stable",
  "name": "gerbil-unstable",
  "summary": "Gerbil Scheme"
}
{
  "repo": "nix_unstable",
  "name": "gerbil",
  "summary": "Gerbil Scheme"
}
{
  "repo": "nix_unstable",
  "name": "gerbil-unstable",
  "summary": "Gerbil Scheme"
}
{
  "repo": "void_x86_64",
  "name": null,
  "summary": "Opinionated dialect of Scheme designed for Systems Programming"
}
{
  "repo": "openbsd",
  "name": null,
  "summary": "dialect of Scheme designed for systems programming"
}
```

These `gerbil` packages are a completely different program:

```json
{
  "repo": "aur",
  "name": null,
  "summary": "An interactive visualization tool targeted at multispectral and hyperspectral image data"
}
{
  "repo": "macports",
  "name": null,
  "summary": "Hyperspectral Image Visualization & Analysis Framework"
}
```

**Comment by lassik** [comment]
Package `ol` in `void_x86_64` is the same as `owl-lisp` in all the other repos.

**Comment by lassik** [comment]
The `freebsd` package `petite-chez` is the same as `petite-chez-scheme`.

Since the main Chez Scheme package is canonicalized to `chez-scheme` in Repology, we should probably canonicalize the Petite version as `petite-chez-scheme` for consistency?

**Comment by lassik** [comment]
[Copied from #410]

Most of the Repology `chicken` packages are Chicken Scheme. However:

* The packages merged under `chicken` whose binname and visiblename are `chicken-feathers` are an optional extension to Chicken Scheme. They are not to the same package as the main Chicken Scheme package. The `chicken-feathers` packages currently exist in the Alpine repos.

* The `homebrew` package `chicken` is Chicken Scheme, but the `homebrew_casks` package `chicken` is a VNC client (https://sourceforge.net/projects/chicken/), a different and unrelated program.

* The repology package `chicken-scheme` (currently only featured in openwrt) is Chicken Scheme.

**Comment by lassik** [comment]
`ypsilon` and `ypsilon-scheme` are the same package.

**Comment by lassik** [comment]
`scheme9` and `scheme-9-from-empty-space` are the same package.

**Comment by lassik** [comment]
`loko` and `loko-scheme` are the same package.

**Comment by lassik** [comment]
The `STk` package in `openbsd` and `pkgsrc_current` is a Scheme implementation. All of the other `stk` packages are the Synthesis Toolkit from CCRMA, an completely different program. It might make sense to coin `stk-scheme` for Repology.

**Comment by lassik** [comment]
`ikarus` and `ikarus-scheme` are the same package.

**Comment by AMDmi3** [comment]
> Package ol in void_x86_64 is the same as owl-lisp in all the other repos.

No, `ol` is otus lisp

> They are not the same package as the main Chicken Scheme package. The chicken-feathers packages currently exist in the Alpine repos.

Feathers are indeed a part of the main chicken scheme package. In alpine they come from the same PKGBUILD.

**Comment by lassik** [comment]
> > Package ol in void_x86_64 is the same as owl-lisp in all the other repos.
> 
> No, `ol` is otus lisp
> 
> > They are not the same package as the main Chicken Scheme package. The chicken-feathers packages currently exist in the Alpine repos.
> 
> Feathers are indeed a part of the main chicken scheme package. In alpine they come from the same PKGBUILD.

I stand corrected on both counts. Sorry about the mistakes.

**Comment by lassik** [comment]
After commit `6f27069` two packages now belong to `chibi-unclassified`:

https://packages.altlinux.org/en/p9/srpms/chibi
https://packages.altlinux.org/en/sisyphus/srpms/chibi

Both of these are Chibi-Scheme, as evidenced by grepping for `scheme` on those web pages.

**Comment by lassik** [comment]
The rest of the above changes all look exactly right to me.

**Comment by lassik** [comment]
`gscheme` and `gnustep-gscheme` are the same package.

**Comment by lassik** [comment]
`nanopass-scheme` and `nanopass-framework-scheme` are the same package.

**Comment by lassik** [comment]
The `rosa_2014_1` package `plt` is the same package as `plt-scheme`.

The `rpmsphere` package `plt` is a different, unrelated program.

The `drscheme` package (only in `gobolinux`) appears to be the same package as `plt-scheme`. https://github.com/gobolinux/Recipes/blob/master/DrScheme/371/Recipe downloads `plt-371-src-unix.tgz` and runs its configure script, apparently with default settings.

That concludes the list of Schemes I have on record.

**Comment by AMDmi3** [comment]
> After commit 6f27069 two packages now belong to chibi-unclassified

As expected for repositories which do not provide homepage information.

> After commit 6f27069 two packages now belong to chibi-unclassified

Doesn't it make sense to merge it into `racket`?

**Comment by lassik** [comment]
> > After commit [6f27069](https://github.com/repology/repology-rules/commit/6f27069cc92ac6252e14970bdca95604ed399bbe) two packages now belong to chibi-unclassified
> 
> As expected for repositories which do not provide homepage information.

OK, I get the matching system now. So if that package repo started providing homepage info those packages would be automatically moved under `chibi-scheme`. Excellent.

> > After commit [6f27069](https://github.com/repology/repology-rules/commit/6f27069cc92ac6252e14970bdca95604ed399bbe) two packages now belong to chibi-unclassified
> 
> Doesn't it make sense to merge it into `racket`?

PLT Scheme is the previous Scheme system made by the research group that makes Racket. I'm not sure how much code there is in common; it's safe to assume the current Racket has added and modified a huge amount of stuff since the last release that was made under the name PLT. For that reason, it's probably best to keep Racket and PLT separate. I'm not sure why some distros still ship PLT; the authors and most users have moved on to Racket.

On the other hand, merging PLT Scheme and DrScheme is probably safe. DrScheme is one component of PLT Scheme (the IDE), but I'm not sure whether it even runs if the rest of PLT isn't installed.

**Comment by AMDmi3** [comment]
So as far as I can see, we're done here.

**Comment by lassik** [comment]
Yes, everything is correct. Thank you very much for the prompt response. Repology is an extremely useful site and you take excellent care of your project!
