### ISSUE TITLE
unrar version scheme

### ISSUE THREAD

**Issue by sunpoet** [repology/repology-rules#412]
https://repology.org/project/unrar/versions

The unrar version does not follow the tarball name.
For example, unrar-5.9.4.tar.gz is actually unrar 5.91.
```
% cat version.hpp
#define RARVER_MAJOR     5
#define RARVER_MINOR    91
#define RARVER_BETA      0
#define RARVER_DAY      25
#define RARVER_MONTH     6
#define RARVER_YEAR   2020
```
Running unrar shows:
UNRAR 5.91 freeware      Copyright (c) 1993-2020 Alexander Roshal

**Comment by AMDmi3** [comment]
Upstream issue
