### ISSUE TITLE
k3s - Nixpkgs

### ISSUE THREAD

**Issue by theduke** [repology/repology-rules#413]
[k3s](https://github.com/rancher/k3s) is [present in nixpkgs](https://search.nixos.org/packages?show=k3s&query=k3s&from=0&size=30&sort=relevance&channel=unstable#disabled) with the name `k3s`, yet it is not detected on the website: https://repology.org/project/k3s

I scanned the Docs page and the README but couldn't find a direct answer how to adjust the config for this.

**Comment by AMDmi3** [comment]
It has empty version.

**Comment by Atemu** [comment]
This is an issue on our side, continued in the issue above.

**Comment by AMDmi3** [comment]
Not repology issue

**Comment by Atemu** [comment]
Should also be fixed with the next eval and unstable advancement.
