### ISSUE TITLE
A few packages need some rules

### ISSUE THREAD

**Issue by TimB87** [repology/repology-rules#416]
Hi @AMDmi3 
Beforehand, sorry to not open a PR with those suggested rules, but I'm a little short handed right now.

I have a list of packages that I am carrying around for a while that kept growing a bit. Also some points might be up to discussion, we'll see.

1. discord-ptb
  - This is compared to a windows build version and they are not comparable.
2. steam
  - Same problem as 1
3. arpon
  - stripping -ng from the version actually alters the real name. I feel like this not desirable, any thoughts?
4.  dsniff
  - this too strips b1, which isn't a beta marker here, so "2.4b1" is the correct last version
5. dokuwiki
  - alters the version string which equals the release date to use hyphens to make YYYY-MM-DD more clearer, still alters the version string, imo illegally.
  - in practice this means for the CRUX Pkgfile of the port to introduce a second helper variable to download the source tar correctly
6. paper
  - two projects share the same name, but one is specifically targeted towards macos if I understand it correctly. This is not comparable
7. moc
  -  this is a beta version. Even though the lattest tag is somewhat dated, this is not the latest release.
8. xtables-addon
  - latest version is "3.11", nothing else
9. john
  - again, alters the official tag and strips "jumbo-1" from it
10. xdg-utils
  - latest version is "1.1.3", not "1.1.5"
11. networkmanager
  - this is not an official release
12. network-manager-applet
  - this is not an official release either
13. noto-emoji
  - this too alters the version string and strips, imo, valuable information about it in that case
14. libstemmer/snowball
  - am I missing something? [v.2.0.0 is an official commit](https://github.com/snowballstem/snowball/releases/tag/v2.0.0)

What do you think?

**Comment by AMDmi3** [comment]
> stripping -ng from the version actually alters the real name. I feel like this not desirable, any thoughts?

The meaningless suffix is an upstream problem so I think we can just strip it, and also merge arpon-ng into arpon. Upstream downloads don't even list pre -ng versions so I take it as they can safely be assumed outdated.

> this too strips b1, which isn't a beta marker here, so "2.4b1" is the correct last version

Looks like a beta marker for me ([https://monkey.org/~dugsong/dsniff/**beta**/](https://monkey.org/~dugsong/dsniff/beta/) and homepage says latest is 2.3). Stripping it is definitely incorrect, marking it as devel is required.

> dokuwiki

Looks pretty clear to me that upstream uses YYYY-MM-DD. Using that scheme is also crucial to [match it against NVD](https://repology.org/project/dokuwiki/cves).

> noto-emoji

Not seeing any problems.

> libstemmer/snowball

The rules is from 2018, the release is from 2019 so it's just outdated.

**Comment by AMDmi3** [comment]
All issues should be fixed.
