### ISSUE TITLE
scrot needs splitting

### ISSUE THREAD

**Issue by dylanaraps** [repology/repology-rules#422]
There are two different "scrot" utilities packaged by distributions. One is the original project which has its latest version at `0.8`, the other is a forked project which continued development. According to Repology, Fedora, OpenBSD, Slackware and KISS (among others) only include the 0.8 version, while other distributions use the fork or some combination of the two.

The 0.8 version works without issue and is quite different from the fork. The package should be split as one is the original upstream and the other is a fork.

**Comment by AMDmi3** [comment]
Original project is dead, while the fork is well maintained. There's no reason to treat abandonware specially.
