### ISSUE TITLE
seafile: incorrect category match

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#425]
https://repology.org/project/seafile/versions

There are 3 "seafile" packages: 
https://github.com/haiwen/seafile-server/ (server community version)
https://download.seafile.com/d/6e5297246c/?p=/pro (server pro version)
https://github.com/haiwen/seafile-client/ (client)

Currently, Wikidata refers to a seafile-server community edition, while all other repository refer to seafile-client

**Comment by AMDmi3** [comment]
You can fix it directly in wikidata

**Comment by blshkv** [comment]
ok, fixed. Thanks
