### ISSUE TITLE
`num` package is not detected as `ocaml-num` for Fedora distribution

### ISSUE THREAD

**Issue by XVilka** [repology/repology-rules#426]
Fedora has `ocaml-num` package, but Repology doesn't recognize it as an alias to `num`:
- https://repology.org/project/num/versions (no Fedora)
- https://fedora.pkgs.org/32/fedora-x86_64/ocaml-num-1.1-21.fc32.1.x86_64.rpm.html

**Comment by AMDmi3** [comment]
Will investigate mapping all dev-ml/* packages to ocaml:*
