### ISSUE TITLE
false positive for untrusted

### ISSUE THREAD

**Issue by jonasstein** [repology/repology-rules#434]
`untrusted - this source is known to likely supply incorrect versions, so is ignored proactively.`

I think this is a false positive in
xkeycaps 2.47_p7
on
https://repology.org/projects/?maintainer=desktop-misc%40gentoo.org&inrepo=gentoo&problematic=1

**Comment by AMDmi3** [comment]
There's no upstream version 2.47_p7, so it's totally correct.

**Comment by jonasstein** [comment]
_p7 is just a way to note patch 7 in gentoo. Perhaps it would be the best to handle these numbers of gentoo packages differently in the script. https://devmanual.gentoo.org/ebuild-writing/file-format/index.html

**Comment by AMDmi3** [comment]
I'm aware. There's no way to handle it differently - it's compared greater than a normal release according to the documentation, and as it's a fake version it's excluded from comparison by marking it untrusted.
