### ISSUE TITLE
clang versions on Debian/Ubuntu

### ISSUE THREAD

**Issue by joto** [repology/repology-rules#436]
For Debian and Ubuntu distributions the `clang` package version isn't recognized.

**Comment by AMDmi3** [comment]
Maybe because it's llvm? https://packages.ubuntu.com/source/focal/llvm-toolchain-10

**Comment by joto** [comment]
If I look at llvm, I get lots of packages like `llvm-toolchain-9`. I still can't easily see what the newest version is. I would have expected all of these packages to be merged somehow.

**Comment by AMDmi3** [comment]
I don't quite get the problem. Take ubuntu 20.10 - https://repology.org/project/llvm/versions#ubuntu_20_10 - there are 4 versions available, all latest in their respective branches and all contain corresponding version of clang. Btw, I've merged llvm components packaged separately in different distros, but it isn't completely related to debian/ubuntu.

**Comment by joto** [comment]
Sorry, seems I was confused between the different clang and llvm packages and how the merging of the packages work. This looks good now. Thank you!
