### ISSUE TITLE
crackmapexec: pulled from a private source, 30 days delay

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#438]
Ok, here is a tricky one. Kali has a special agreement with the upstream and it pulls a private release
https://repology.org/project/crackmapexec/versions

See more details at:
https://www.kali.org/news/kali-linux-2020-4-release/

Can you NOT show kali package for 30 days?

**Comment by AMDmi3** [comment]
30 days - no, and I don't think I want to implement such complication. May just ignore version from Kali (it automatically becomes latest when any other repo catches up).

**Comment by blshkv** [comment]
I suspect, that agreement won't last. The source is available from Kali mirrors anyway:
http://mirrors.neusoft.edu.cn/kali/pool/main/c/crackmapexec/

So anyone can pull it anyway

**Comment by AMDmi3** [comment]
Then unless someone complains I think we can ignore it.
