### ISSUE TITLE
openjdk: debian experimental shows pre-release openjdk 16

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#439]
https://repology.org/project/openjdk/versions

The latest version is 15.x
https://adoptopenjdk.net/?variant=openjdk15&jvmVariant=hotspot
https://github.com/AdoptOpenJDK

debian experimental has 16.x pre-release. It should not be displayed as the latest official release

**Comment by AMDmi3** [comment]
Adding rule for now, but this should be fixed at some point by repology/repology-updater#811
