### ISSUE TITLE
invalid openjdk version of openSUSE

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#443]
https://adoptopenjdk.net/?variant=openjdk15&jvmVariant=hotspot
openSUSE Tumbleweed shows 16 which was not released

**Comment by AMDmi3** [comment]
Doesn't adoptopenjdk just build binaries? It looks like valid openjdk version https://github.com/openjdk/jdk/tags, but not sure regarding tags.

**Comment by blshkv** [comment]
http://openjdk.java.net/projects/jdk/ This is a better link. 16 is not released yet

**Comment by AMDmi3** [comment]
But there is a tag of the same format as for 15.

**Comment by blshkv** [comment]
https://mail.openjdk.java.net/pipermail/jdk-dev/2020-December/004985.html

**Comment by AMDmi3** [comment]
Unfortunately that doesn't clean things up for me.

**Comment by AMDmi3** [comment]
I guess I'd mark the whole mess as noscheme. Tags are in jdk-15+36 format, release versions are in 15.0.1 format, adoptopenjdk versions in 15.0.1+9.1 format, it's a total mess.
