### ISSUE TITLE
Match linux kernels with _ separators too

### ISSUE THREAD

**Issue by Atemu** [repology/repology-rules#445]
In nixpkgs we use _ to separate 'linux' and the variant name for some reason, i.e. linux_rpi1, linux_hardened or linux_zen.

Repology currently only matches - as a separator AFAICT.

I'm not very proficient in regex but stuff like this seems like an easy tweak. How could I go about verifying that a regex works and doesn't accidentally break things it shouldn't?

**Comment by AMDmi3** [comment]
Please point to an example on repology.org.

**Comment by Atemu** [comment]
https://repology.org/project/linux-zen/versions

I maintain that kernel in Nixpkgs but it's called linux_zen and repology thinks it's linux\*.

https://repology.org/projects/?maintainer=atemu.main%2Bnixpkgs%40gmail.com&inrepo=nix_unstable

**Comment by AMDmi3** [comment]
There's nothing about `linux_zen` in nix packages listing
```
% wget -qO- https://channels.nixos.org/nixos-unstable/packages.json.br | brotli -d | grep -o linux_zen
%
```
Repology normalizes `_` to `-` so the separator doesn't matter.

**Comment by Atemu** [comment]
I came across this again and it appears to still be an issue. The Linux kernel variants are now present in the JSON under `linuxKernel.kernels.*` however.

**Comment by AMDmi3** [comment]
Please point to an example on repology.org.

**Comment by Atemu** [comment]
The example still applies: https://repology.org/project/linux-zen/versions

**Comment by AMDmi3** [comment]
Zen kenrle ends up in plain `linux` project because `pname = linux`.

**Comment by Atemu** [comment]
Indeed. I'll see to get that fixed.

Does that mean pname is all that counts for Repology matching?

**Comment by AMDmi3** [comment]
> Does that mean pname is all that counts for Repology matching?

pname is what project name is derived from, yes. Rules may look at other fields (category, upstream urls), but I don't see anything which can be used here reliably.
