### ISSUE TITLE
aget isn't necessarily the same as aget

### ISSUE THREAD

**Issue by berolinux** [repology/repology-rules#448]
https://repology.org/project/aget/versions shows anything but AUR using an "outdated" 0.4.x version, while AUR has 1.0.

This is actually 2 different things: AUR has this (aget -- AUR get -- retrieve a package from AUR): https://github.com/xyproto/aget (which is at 1.0)
The other distributions have this: http://www.enderunix.org/aget/ (multi-threaded HTTP download accelerator). The current version of this is 0.4.1.

There should be some rule preventing aget 0.4.1 from being marked as obsoleted by the other aget.

**Comment by AMDmi3** [comment]
Fixed in 77e4d3b532b50b07058e226ffe1d34896138e1f7
