### ISSUE TITLE
Nixpkgs: vapoursynth is not detected

### ISSUE THREAD

**Issue by rnhmjoj** [repology/repology-rules#453]
I'm a maintainer of the vapoursynth package in Nixpkgs. The package has existed for a number of years and is listed in the [packages.json.br](https://releases.nixos.org/nixos/20.09/nixos-20.09.2624.1eff582e7ea/packages.json.br) file, but Repology report it's missing in Nixpkgs (either stable or unstable).

What's going on?

**Comment by AMDmi3** [comment]
Niether vapoursynth nor vapoursynth-editor has `version` defined. For instance, varpoursynch-mvtools is properly tracked: https://repology.org/project/vapoursynth:mvtools/versions#nix_stable

**Comment by rnhmjoj** [comment]
Thank you, we figured it's a problem in the parser of the package version.
