### ISSUE TITLE
Request for version normalizations for package 0ad

### ISSUE THREAD

**Issue by tuxayo** [repology/repology-rules#466]
https://repology.org/project/0ad/versions

Arch: a24.b isn't marked as the latest version but it's indeed the right one (alpha 24b)
Same for
- KaOS
- Manjaro
- Parabola

For Npackd Stable 0.0.24.2 is actually also alpha 24b

**Comment by AMDmi3** [comment]
We don't normalize incorrect version schemes. `24.2` and `24.b` instead of `24b` are indeed incorrect.
