### ISSUE TITLE
Fix PyPI entry in python:snappy

### ISSUE THREAD

**Issue by slel** [repology/repology-rules#467]
The PyPI entry on the page

- https://repology.org/project/python:snappy/versions

should refer to

- [python-snappy](https://pypi.org/project/python-snappy/) - Python bindings for the snappy compression library from Google

instead of the currently listed

- [snappy](https://pypi.org/project/snappy/) - topology and geometry of 3-manifolds

which could either become a new entry (maybe snappy-geometry or snappy-manifolds)
or be dropped, as it is currently not packaged in any distribution (apart from being listed
as an optional package in the SageMath distribution since SageMath 9.3.beta8).

**Comment by AMDmi3** [comment]
No, PyPI entry is in fact the only correct one on that page (`snappy` pypi package goes to `python:snappy`, `python-snappy` pypi package goes to `python:python-snappy`). Repositories mix up prefix they use for python packages and the module name and should fix it.
