### ISSUE TITLE
Remove wrapped packages from Nixpkgs?

### ISSUE THREAD

**Issue by jtojnar** [repology/repology-rules#484]
In nixpkgs we often have packages that combine a package with its plugins:

https://repology.org/projects/?search=-with-plugins
https://repology.org/projects/?search=-with-extensions
https://repology.org/projects/?search=-wrapper&inrepo=nix_unstable – this sometimes occurs in project names so perhaps only uniques should be skipped

Would it make sense to filter them out?

**Comment by AMDmi3** [comment]
What do you mean by filtering out? These should generally be merged into corresponding projects with unsuffixed names, but for that there's need to reliably strip the suffixes. As far as I can see that's not even possible for `-with-plugins` because there may be multiple suffixes.

**Comment by jtojnar** [comment]
I meant something like:

```yaml
- { ruleset: nix, namepat: ".+-with-plugins", remove: true }
- { ruleset: nix, namepat: ".+-with-extensions", remove: true }
- { ruleset: nix, namepat: ".+-wrapper", unique: true, remove: true } # not sure how to express to only remove packages unique to Nixpkgs since there are some real projects with this namepat
```

Those packages really are just a pseudo-package that allows user to use a package with specific plug-ins enabled and have little to do with the project. For example, `inkscape-with-plugins` currently installs `inkscape-1.0.1`, `hexmap-2020-06-06` and `inkcut-inkscape-plugin`.

But yeah, there can be multiple suffixes as in `asciidoc-full-with-plugins`. We might want to standardize a metadata format for descriptions on our side first.

Feel free to close this until then.

**Comment by AMDmi3** [comment]
If these are pseudo-packages, it makes sense. `-wrapper` case needs small core changes repology/repology-updater/issues/1151 to be able to only hide uniques.

**Comment by AMDmi3** [comment]
Although wait, how about this one: https://repology.org/project/zathura/versions#nix_stable. There's no package without plugins.

**Comment by jtojnar** [comment]
You are right, that is messier than I realized. Some programs are useless without plug-ins so there is no unwrapped package exposed. I guess there is nothing to do until we standardize this in Nixpkgs.

**Comment by AMDmi3** [comment]
Ok, leaving it as is for now.
