### ISSUE TITLE
openSUSE: unknown source for libc*/libf* libraries

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#489]
Hello, openSUSE bumped all libc* libf* libraries (https://github.com/libyal/*), but the source is unknown. As a wild guess, they created new snapshots, but called it "official release" for some reason:

https://repology.org/projects/?inrepo=gentoo_ovl_pentoo&outdated=1
https://github.com/libyal/libcdata/releases
https://software.opensuse.org/package/libcdata

But there are some new versions, but they don't match with opensuse: 
- libvshadow-alpha-20210425 (not 20210507)
- libfwnt - 20210421
 - libclocale - 20210526
 - libsmdev - 20210418
may be more

**Comment by jengelh** [comment]
Please undo this - or improve the check. https://repology.org/project/libfsapfs/versions 20221102 is shown in black for openSUSE, despite 20221102 being an actual tagged release on Github.

**Comment by AMDmi3** [comment]
Unfortunately `untrusted` rules stay forever to avoid fake new versions in the future.

**Comment by jengelh** [comment]
Well let's just say then... that's interesting attack vector for a denial of "practical service" there.

**Comment by AMDmi3** [comment]
On the contrary, the idea is to reliably prevent misbehaving repositories which report made up versions from disrupting a normal service of reporting official releases. The drawback is negligible - even if correct new version is blocked, it will be reported just a bit later when another, trusted, repository catches up. This measure is justified, as single fake release affects all maintainers in other repos and repology staff as well. The only attack vector here is for repository to pessimize itself, but I don't see any sense in that.

**Comment by blshkv** [comment]
It should be an official openSUSE version policy review and official explanation that it won't happen again. There is no point reverting rules here if the policy hasn't changed, as there is a high chance that openSUSE would do it again.

**Comment by jengelh** [comment]
At least for the four packages you listed, we have been using the version number *upstream conveyed through configure.ac* (with 0~ in the early stages where there was uncertainty about libyal's direction). The value in configure.ac is used for `@VERSION@` substitutions,

```
include/libvshadow/definitions.h.in:#define LIBVSHADOW_VERSION                  @VERSION@
```

and it is the version number *reported by command-line utilities* such as:

```
$ vshadowinfo 
vshadowinfo 20210507

Missing source file or device.
Use vshadowinfo to determine information about a Windows NT Volume Shadow
Snapshot (VSS) volume
```

Getting the repology black marker for making the version of the RPM package match what the source code thinks of itself... is unjust.

`security:forensics` is one of the feeder repositories for `openSUSE:Tumbleweed`. Tumbleweed cannot ship a version that was not in `forensics` first. So I will (only) look at our build history log for `forensics` below.

>But there are some new versions, but they don't match with opensuse:
>libvshadow-alpha-20210425 (not 20210507)

```
$ osc buildhist security:forensics/libvshadow openSUSE_Tumbleweed x86_64
time                  srcmd5(obs)                         vers-rel.bcnt    rev   duration
2021-06-09 00:01:20   f9f9875df2a32429172a6ab19394cfb1    0~20201222-26.10 22         84
  -- rev 22 used release tarball libvshadow-alpha-20201222.tar.gz
  -- its configure.ac contains AC_INIT([libvshadow], [20201222])
  -- URL was https://github.com/libyal/libvshadow/releases/download/20201222/libvshadow-alpha-20201222.tar.gz
  -- returns 404 today(?), looks like J.Metz deleted the old releases from Github
2021-06-09 10:34:56   610d7f935aea0df3f47799d2cacfa417    20210507-27.1    23         71
  -- rev 23 used git commit 9f06d799bb6551061eee281ca985daa0fbdae011
  -- configure.ac has AC_INIT 20210507
```

>libfwnt - 20210421

```
2021-06-01 20:55:03   f33756a3c20be3f45b11b2b3c4f8e1db    0~20200723-19.8  19        114
  -- rev 19 used a release tarball libfwnt-alpha-20200723.tar.gz
  -- configure.ac has AC_INIT 20200723
2021-06-09 09:55:03   a5591fc027d704046ed5e23e3223fc0f    20210421-20.1    20         87
  -- rev 20 used git snapshot fa9d27e506cf221d803adce4ab7145b6b2ecca05
  -- configure.ac has AC_INIT 20210421
2021-06-11 13:54:28   60c08167a96e60c66131f03749c7b0dd    20210421-21.1    21        119
  (source unchanged)
2021-07-22 02:22:26   c99cef7b54dbd24a6a18016f19046b66    20210717-22.1    22         91
  -- rev 22 used a Github-generated tarball of tag 20210717
  -- configure.ac has AC_INIT 20210717
```

>libclocale - 20210526

```
2021-06-01 19:21:43   32f085ff3638466f40f5db3725f945ee    0~20200913-1.5   7         89
  -- rev 7 used release tarball libclocale-alpha-20200913.tar.gz
  -- configure.ac has AC_INIT 20200913
2021-06-06 01:48:38   df845830f14229dfa68145ac05970eac    20210410-1.1     8         77
  -- rev 8 used git snapshot 305803c63f46be76b396d9891cb2898b00f7a216
  -- configure.ac has AC_INIT 20210410
2021-06-26 11:11:13   4916e4ab1c75e7f36024c578d08f74c9    20210526-1.1     9         87
2021-11-14 12:52:05   6793a2c2f99c3865fe9ead4b865c166d    20210526-2.1     10         86
2021-11-14 14:28:19   fc749147367ad0d9354d2e4e1749d6ce    20210526-3.1     11         93
2021-11-25 18:47:44   0d0957b850cbf6468ad217788e2d18d4    20210526-4.1     12         45
2021-11-25 21:47:09   9c3b5e51d7d886eab43b56b91583c0a7    20210526-5.1     13         76
2021-12-14 21:40:42   9c3b5e51d7d886eab43b56b91583c0a7    20210526-5.2     13        198
  -- revs 9..13 used release tarball libclocale-alpha-20210526.tar.gz
  -- configure.ac has AC_INIT 20210526
2022-01-08 10:54:09   fdd344dd684f7deec1692af481842013    20220107-1.1     14         37
  -- rev 14 uses release tarball libclocale-alpha-20220107.tar.gz
```

>libsmdev - 20210418

```
2021-06-08 23:59:42   4bb3f6427fc2bb341091f50d05d9a7c3    0~20201204-18.10 15         63
 -- r15 used release tarball libsmdev-alpha-20201204.tar.gz
 -- configure.ac has AC_INIT 20201204
2021-06-09 10:25:13   be7485659f5c7b09fef63e8060f6838c    20210418-19.1    16         55
2021-06-11 14:34:24   eaa49370112138f1278db479dd5454c6    20210418-20.1    17         74
2022-01-24 12:41:53   f24c9283b027aabbd12f9a14d3f0b391    20210418-21.1    18        143
2022-01-24 23:53:33   8abe466fd836b6d518a3fb6559d5c00e    20210418-22.1    18        294
2022-08-09 08:12:30   f3a35e169c172b81db0f24add99374aa    20210418-23.1    19        147
2022-08-09 19:34:20   7f542b9bf17a327b3c6a54972474331c    20210418-25.1    20        137
  -- r16..r20 used git snapshot 3b84f9f752b37867985565e58768bab146026065
  -- configure.ac has AC_INIT 20210418
2022-10-28 12:03:43   cef1920844f70327f346c3f4f169e784    20221028-26.1    21        134
  -- r21 uses release tarball libsmdev-alpha-20221028.tar.gz
  -- configure.ac has AC_INIT 20221028
```

**Comment by AMDmi3** [comment]
> upstream conveyed through configure.ac

Version set in the sources generally cannot be trusted, as (unlike a tag) it does not refer to a single point in time, often it does not correlate with releases, being bumped before the release, being forgotten to be bumped, or being a different value used internally (such as API version). None of these seem to be the case here though - upstream just does [commit per release](https://github.com/libyal/libfcrypto/commits/main) and doesn't bother with tags.

I'm puzzled. To stick to official [tagged] versions and to release newer upstream version (even if not properly arranged) are both valid positions. The upstream is mostly to blame for the mess, so alternative would be to just mark these projects as `noscheme`, but this way we'll lose the updates. Let's discuss.

@blshkv would you consider packaging versions mentioned in `configure`? As these seem to be valid in this case.
@joachimmetz (upstream), would you consider tagging every release of https://github.com/libyal/*? Or are untagged versions not official/stable/ready to use?

**Comment by joachimmetz** [comment]
> The upstream is mostly to blame for the mess, so alternative would be to just mark these projects as noscheme, but this way we'll lose the updates. Let's discuss.

Very constructive way to start a discussion, blame it on upstream.

First of all upstream (me) never asked for these to be distributed in openSUSE, so I would say this is a "mess" that openSUSE is to blame for not upstream.

Second if openSUSE expects certain versioning/distribution methodologies, I find it more than reasonable to first reach out to uptstream before packaging and then blaming outfall on upstream.

> None of these seem to be the case here though - upstream just does [commit per release](https://github.com/libyal/libfcrypto/commits/main) and doesn't bother with tags.

Not all commits are releases, have a look at https://github.com/libyal/libfcrypto/wiki/Building#read-first

> @joachimmetz (upstream), would you consider tagging every release of https://github.com/libyal/*? Or are untagged versions not official/stable/ready to use?

there are tagged versions (https://github.com/libyal/libfcrypto/tags) why are you even asking this question?

**Comment by AMDmi3** [comment]
> Very constructive way to start a discussion, blame it on upstream.

I'm just trying to resolve an ambiguity of having versions which are only mentioned in the source, but not having corresponding tags. That has nothing to do with openSUSE packaging.

> there are tagged versions (https://github.com/libyal/libfcrypto/tags) why are you even asking this question?

I'm asking this question because there are versions such as [20221010](https://github.com/libyal/libfcrypto/commit/29fac77672607bfd2c76d55a5880f1086c8495d5#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810R5), [20220903](https://github.com/libyal/libfcrypto/commit/05aeb6dec42cdd66a696cecaaa75f1229dc91b63#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810R5), [20220710](https://github.com/libyal/libfcrypto/commit/fb5fbe866c042f1fdd5eca11731927db2e8fd240#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810R5) which do not have corresponding tags.

**Comment by jengelh** [comment]
> Version set in the sources generally cannot be trusted, as (unlike a tag) it does not refer to a single point in time

There is another consideration to be made, away from AC_INIT.

Distributions can and do apply patches on top of published tags/tarballs. The result still carries the original version number. Whether a distro uses, for example, `libX11-1.8.1.tar.gz` and then applies fix patch `c601c779-nls-delete-compose-sequences-that-mix-top-row-digits.patch` during build on top, or whether a distro runs `git-archive c601c779` should not make a difference to repology.

**Comment by AMDmi3** [comment]
> should not make a difference to repology

Repology compares package versions, not package contents, and it would make no sense to do otherwise, as random codebase snapshots with or without patches applied cannot be ranked by any useful metric. Upstreams which fail to provide comparable monotonic versions and repositories which fail to convey upstream versions undistorted are out of Repology scope.

**Comment by blshkv** [comment]
@AMDmi3 I really don't care at this point. The upstream is uncooperative (hi @joachimmetz ) with a lot of "unsupported", " not intended to be redistribute-able" and "expect you to fix your problem yourself"
https://github.com/libyal/libvshadow/issues/10#issuecomment-461338774
https://github.com/libyal/libuna/issues/7#issuecomment-316605771

He also expects libc* to be in one directory: "This also only appears to be an issue for distro package maintainers that, against advice, want to deploy every libyal library as a shared object."

**Comment by joachimmetz** [comment]
[@AMDmi3](https://github.com/AMDmi3) why should I provide? Why should I help a person that appears to only can communicate in a rude and nonconstructive way?

>He also expects libc* to be in one directory: "This also only appears to be an issue for distro package maintainers that, against advice, want to deploy every libyal library as a shared object."

yes, what is this obsession that every library should be a shared library? It makes no sense. Source code management, deployment and distribution are 3 different things that should not be confused. Why do distribution maintainers insist on convolution this.

Leave me out of this discussion, and come back when you can behave.

**Comment by AMDmi3** [comment]
Okay, marked libyal & friends as noscheme.
