### ISSUE TITLE
forgotten reports?

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-rules#49]
Several reports haven't been answered:

perl:exporter-tiny (16 days old)
perl:io-tty (16 days old)
perl:xml-namespacesupport (16 days old)
python:enum (16 days old)

I don't know if there was a huge long queue and they are stilll in line, but it seems more likely that they've been overlooked.

**Comment by AMDmi3** [comment]
They are not forgotten. They are all actual devel versions, I haven't yet investigated whether it can be solved by adding a single rule for AOSC for all perl modules containing plus sign, and/or whether it's possible to get a list of devel versions from metacpan. Either would help. I guess I'll just add individual rules for the time being.

**Comment by jrmarino** [comment]
thanks

**Comment by AMDmi3** [comment]
Let's leave this, as a reminder that the proper fix is still desired.

**Comment by AMDmi3** [comment]
MetaCPAN is now supported along with devel versions from it.
