### ISSUE TITLE
burpsuite: stable vs early adopter

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#490]
There are two lines of burpsuite:
https://portswigger.net/burp/releases
The stable version should be 2021.5.x, I marked 2021.6.x as ```_pre```

it is difficult to differentiate between two because the jar file doesn't reflect it.
So I'm not sure what can be done, what's your take? Contact vendor?

**Comment by AMDmi3** [comment]
> So I'm not sure what can be done, what's your take? Contact vendor?

Would be nice. On repology side, I'm marking 2021.6 as devel, but it would have to be updated as soon as 2021.6 is considered stable. `_pre` suffix is fake and would make `2021.6.1_pre` compare less than official `2021.6.1`.

**Comment by blshkv** [comment]
https://forum.portswigger.net/thread/differentiate-burp-releases-19ecf9bf

**Comment by blshkv** [comment]
so the upstream said "this isn't something we can do at this time". Can you mark it as release-candidate perhaps? ```_rc``` suffix?

**Comment by AMDmi3** [comment]
2021.6.1 is already classified as devel. What else needs to be done?

**Comment by blshkv** [comment]
I was asking if you would consider to mark ```_rc``` ebuilds as devel?

Also, 2021.6.2 is stable now, see https://portswigger.net/burp/releases/professional-community-2021-6-2

**Comment by AMDmi3** [comment]
> I was asking if you would consider marking our _rc ebuilds as devel?

`rc`s are devel by default. But they will compare less than suffixless versions, thus be classified as outdated.

> Also, 2021.6.2 is stable now, see https://portswigger.net/burp/releases/professional-community-2021-6-2

I expect pull requests for projects which require continuous rule updates.
