### ISSUE TITLE
merge ifuse packages

### ISSUE THREAD

**Issue by waldyrious** [repology/repology-rules#502]
https://repology.org/project/ifuse should be merged with https://repology.org/project/fusefs:ifuse. If I'm reading [800.renames-and-merges/fusefs.yaml](https://github.com/repology/repology-rules/blob/786c34bdc3afd490bc5e048c555e0ae11bc73c2e/800.renames-and-merges/fusefs.yaml), the canonical name should be `fusefs:ifuse`. Is that correct?

**Comment by AMDmi3** [comment]
> the canonical name should be fusefs:ifuse. Is that correct?

Yep.
