### ISSUE TITLE
Wikidata: incorrect version for fvwm

### ISSUE THREAD

**Issue by alarixnia** [repology/repology-rules#517]
**Project(s)**

https://repology.org/project/fvwm/versions

**Versions to ignore**

Wikidata (3-1.0.1)

**Comments**

1.0.1 is valid for https://repology.org/project/fvwm3/versions only. "3-1.0.1" is not valid for anything.

**Comment by AMDmi3** [comment]
Wikidata is publicly editable, so the problem should be fixed there.
