### ISSUE TITLE
List of LuaRocks packages looks incomplete

### ISSUE THREAD

**Issue by ligurio** [repology/repology-rules#521]
There is a rock unreliablefs, see http://luarocks.org:8080/modules/ligurio/unreliablefs
but this rock cannot be found in https://repology.org/projects/?search=&maintainer=&category=&inrepo=luarocks&notinrepo=&repos=unreliablefs&families=&repos_newest=&families_newest=

However, search found a FreeBSD port of unreliablefs, see https://repology.org/project/fusefs:unreliablefs/versions

**Comment by AMDmi3** [comment]
It is there, it's just not shown in the search because it's only present in luarocks. Will merge into `fusefs:unreliablefs`.

**Comment by ligurio** [comment]
@AMDmi3 Thanks!
