### ISSUE TITLE
merge opentype sanitizer

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [repology/repology-rules#531]
**Source projects**

https://repology.org/project/python:ots-python/versions
https://repology.org/project/python:opentype-sanitizer/versions
https://repology.org/project/python:ots/versions

**Preferred target project**

(no preference)

**Comments**

No comments

**Comment by AMDmi3** [comment]
python:ots != python:opentype-sanitizer, so not merging that part

**Comment by Alessandro-Barbieri** [comment]
Fedora python-ots is in fact ots-python
See https://src.fedoraproject.org/rpms/python-ots/blob/rawhide/f/python-ots.spec#_1
