### ISSUE TITLE
openssl legacy version doesn't look right

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-rules#560]
From Ravenports, 14 NOV 2021 @ 10:47 CST

![image](https://user-images.githubusercontent.com/1125622/141690071-cbefa8bb-d15f-4767-87f0-7e8ad19ef1e7.png)

The 1.1.1 branch, currently at "l" version showing outdated.  It's not clear why.

![image](https://user-images.githubusercontent.com/1125622/141690119-3395dd8a-9199-41ad-bc96-cd25eee0b53a.png)

I'm not sure if there is a rule problem or what, but the expected behavior for me is that "1.1.1l" would be colored orange, meaning it's a legacy branch that is up-to-date.

**Comment by AMDmi3** [comment]
Right, it looks like there's a problem here. Will investigate.

**Comment by AMDmi3** [comment]
The cause is that the port is named `openssl-devel`. For packages which explicitly state they are devel/unstable version the legacy status is suppressed.
