### ISSUE TITLE
Merge various fontsrecommended packages

### ISSUE THREAD

**Issue by slel** [repology/repology-rules#565]
**Source projects**

- https://repology.org/project/texlive-fontsrecommended/versions
- https://repology.org/project/texlive:collection-fontsrecommended/versions
- https://repology.org/project/texlive-collection-fontsrecommended/versions

**Preferred target project**

(no preference)

**Comments**

(no comment)

**Comment by AMDmi3** [comment]
Does it make sense given that it's not even a real package?
