### ISSUE TITLE
Qt* subpackages not listed 

### ISSUE THREAD

**Issue by mambasoft** [repology/repology-rules#566]
Hi Dmitry,
I noticed that Qt6 (and Qt5 although less actual) packages from distributions are not listed except for some Arch packages.
Qt5/Qt6 packages are usually packaged using source submodules available, e.g. here: https://download.qt.io/official_releases/qt/6.2/6.2.1/submodules . Arch Linux calls them, for instance, qt6-declarative, while Fedora and openmamba would call this qt6-qtdeclarative. Could some rule fix this?
Thanks!

**Comment by AMDmi3** [comment]
These are merged into `qt`

**Comment by mambasoft** [comment]
I see, but as such they appear, I think, as multiple package providing the same thing with different name and versions.
Indeed those are submodules so maybe a qt:<submodulename> scheme like used for other languages/frameworks would be better, just a suggestion.

**Comment by AMDmi3** [comment]
No, these are part of qt, and are not even required to be packaged separately.

**Comment by mambasoft** [comment]
Ok, I understand your logic. I will sort out things differently on my side to check the list of all the qt* SRPMS out of date. Thanks for your reply.

**Comment by AMDmi3** [comment]
How is the current setup not suitable for you? Subpackages are merged in such a way that each outdated subpackage will have `outdated` status (not `legacy` as it would be for multiple versions of at in a same repo). It's handled the same way as any other project which may consist of multiple parts. Presence of outdated status would mean some submodule is outdated, and you can check which one on the `information` page. All `newest` statuses correspondingly mean that all subpackages are up to date.

**Comment by mambasoft** [comment]
I use this type of API call: https://repology.org/api/v1/projects/q/?inrepo=openmamba&outdated=1 .
As you say all qt subpackages here are listed with outdated status so I need to change my code and dig into each subpackage and schedule update, currently only the first one (qt6-qtbase) is getting updated. This used to work for most projects (specially kde plasma/frameworks/applications) so I did not care before but maybe implementing this on my side will reveal more updates on other subpackages merged into one project.

**Comment by AMDmi3** [comment]
> but maybe implementing this on my side will reveal more updates on other subpackages merged into one project

Well, yes - you should check status of each package. As far as I remember even the order is not guaranteed.
After a quick glance I can see other projects affected: spyder, usermin, synfig, qscintilla, mozjs, vim, libreadline, telepathy-glib - lots of them in fact.

**Comment by mambasoft** [comment]
Most of the subpackages in those projects are legacy packages which are excluded by using [this list ](https://openmamba.org/pub/openmamba/devel/legacy).

I've improved my script and here is the short and clean list of new findings (those in the last column), which is what I wanted:

```
atom 1.58.0 atom-bin
boost-jam 1.77.0 libboost (?)
certbot 1.21.0 python-acme
clang 13.0.0 compiler-rt,lld,lldb,llvm,libcxx
python-QScintilla 2.13.1 qscintilla
qt6-qtbase 6.2.2 qt6-qt3d,qt6-qtcharts,qt6-qtdeclarative,qt6-qtshadertools
synfig 1.2.2 synfigstudio
vim 8.2.3753 vim-tiny
```

(except for boost-jam which is maybe not a subproject of libboost with same versione). Thanks again!

**Comment by AMDmi3** [comment]
> Most of the subpackages in those projects are legacy packages which are excluded by using this list

Most would have `legacy` status in Repology so you don't need to exclude them manually. In fact you could try checking them too, as Repology is capable of reporting outdated statuses for legacy branches for [some](https://github.com/repology/repology-rules/blob/master/950.split-branches.yaml) projects. For instance, it would report that openmamba's legacy gtk3 3.24.27 is outdated by 3.24.30.

**Comment by mambasoft** [comment]
This would be great, but I don't have clear how I get the latest version (3.24.30) for my gtk3 package with outdated status.

In the API query I use inside "gtk" there are a lot of packages from different distros, some "gtk3" or "gtk+3" packages are "outdated" while others are "legacy" and I don't understand the difference. I could look for the highest 3.x.x version in other packages but that could be quite complex (doing so I would get maybe 3.96.0). For newest packages I do it as simple as filtering packages with "newest" status and I know that they will all have the same latest version (in this case detecting which is the latest stable version is left to the "magic" of repology).

**Comment by AMDmi3** [comment]
> This would be great, but I don't have clear how I get the latest version (3.24.30) for my gtk3 package with outdated status.

That is currently not possible. Only status is reported.
