### ISSUE TITLE
Ignore homeassistant-test-* packages from nixpkgs

### ISSUE THREAD

**Issue by mweinelt** [repology/repology-rules#591]
**Projects affected**
nixpkgs

**Observed behavior**
We recently split off tests into individual packages, so we could do partition test runs better on dependency updates. That resulted in over 500 additional packages, that are only tests of the original home-assistant package.

https://repology.org/projects/?search=homeassistant

**Expected behavior**
Ignore packages starting with prefix `homeassistant-test-` .

**Comment by AMDmi3** [comment]
What behavior do you imply by **ignore** here? I don't see a need for any action regarding these packages.

**Comment by mweinelt** [comment]
They're not really packages, they are just parts of the home-assistant testsuite that was extracted so they could be tested more easily when related dependencies changed. The home-assistant testsuite is ~15k tests in size and easily takes half and hour to run otherwise, which curbed the motivation of our python maintainers to review many leaf package changes.

**Comment by AMDmi3** [comment]
This still does not answer the question of why you want to ignore them and what exactly you imply by that.

**Comment by mweinelt** [comment]
They don't have any output. They're not useful to endusers.

By ignore I mean that repology should not display them.

**Comment by AMDmi3** [comment]
In that case nix should provide a flag which would allow repology to exclude these. Repology will not maintain a rule for each package not useful for endusers.
