### ISSUE TITLE
Improve chocolatey support

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-rules#6]
Chocolatey support may be improved, as some patterns of version mangling are deterministic:

https://chocolatey.org/docs/create-packages#package-fix-version-notation

When version modifications are supported by repology, such rule may be added for chocolatey:

```
- { family: chocolatey, verpat: "([0-9]+\\.[0-9]+\\.[0-9]+)\\.[0-9]{8}", setver: "$1", unignore: true }
```

**Comment by AMDmi3** [comment]
> When version modifications are supported by repology, such rule may be added for chocolatey:

These **are** supported. It's time to try it.

**Comment by AMDmi3** [comment]
Here's the query:

```
select effname,version,versionclass from packages where repo='chocolatey' and version ~ '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]{8}$' and versionclass != 4;
```

It currently returns 159 packages which is about 10% of project in chocolatey. I'm still hesitant to lift the untrusted status for these, but just dropping the fix part could clean the data up somewhat.

**Comment by luzpaz** [comment]
Also there is an issue with deprecated chocolatey packages that notify the user to redirect to another package. See Kodi for example:
https://repology.org/project/kodi/versions
![image](https://user-images.githubusercontent.com/4140247/61640172-dd404b80-ac6a-11e9-9032-5ec9b77ddf79.png)

on the xbmc page it tells users to use the kodi page instead:
![image](https://user-images.githubusercontent.com/4140247/61640320-1bd60600-ac6b-11e9-940c-094b291c35ca.png)

**Comment by AMDmi3** [comment]
This works as indended. What problem do you see?

**Comment by luzpaz** [comment]
Sorry, forgot to show the issue:

[![Chocolatey package](https://repology.org/badge/version-for-repo/chocolatey/kodi.svg)](https://repology.org/project/kodi/versions)

The problem here is that the legit kodi package is not showing up in the full vertical badge...instead the deprecated xbmc (the original name for the kodi package) is shown.

**Comment by AMDmi3** [comment]
Well, generally there's no point in fixing anything for them as long as they provide garbage instead of versions. Though it may make sense to add a flag which allows badge to report ignored versions. Separate issue please.

**Comment by luzpaz** [comment]
> Though it may make sense to add a flag which allows badge to report ignored versions. Separate issue please.

@AMDmi3 which repo should I open the ticket in?

**Comment by AMDmi3** [comment]
[repology](https://github.com/repology/repology), since it relates to badge generating code, and not the ruleset.

**Comment by luzpaz** [comment]
Done, https://github.com/repology/repology/issues/888

**Comment by luzpaz** [comment]
Made a request to ignore the xbmc package via the repology UI.

**Comment by AMDmi3** [comment]
Nothing to be done here
