### ISSUE TITLE
Ignore patch level on OpenBSD packages

### ISSUE THREAD

**Issue by epsilon-0** [repology/repology-rules#601]
**Projects affected**
OpenBSD packages in general, with a concrete example of schema2ldif - https://repology.org/project/schema2ldif/versions

OpenBSD packages sometimes have a patch level present in their package version, such as `1.3pl20210902` above, which shows up as problematic in repology. This `plXXX` should be ignored and treated as just the version by itself.

**Observed behavior**
`plXXX` is counted in the patch version and leads to the package marked as _problematic_.

**Expected behavior**
Ignore `plXXX` and unmark the problematic setting.

**Comment by AMDmi3** [comment]
`pl` is used in openbsd for upstream versions containing `patch` parts, such as openssh, ntp, lumina, and python:shapely, so we cannot remove it.

**Comment by epsilon-0** [comment]
Oh, OK! Thanks for clarifying.

**Comment by AMDmi3** [comment]
I should probably add that
- As said, it (mixing up the way of conveying upstream version components and local snapshots) is a problem of openbsd repository
- We're handling it (IMO) the most graceful way possible - ignoring `*pl*`, which leads to
  - Snapshots getting `ignored` status - the least penalizing among the ignored statuses family, and the same as we're using for snapshots in any other repo
  - Upstream `p{,atch,post}` versions getting ignored (again, the least penalizing) status when coming solely from openbsd, but getting expected status when there's matching `p*` version from any other repo
- See https://github.com/repology/repology-updater/issues/345 for ideas/discussion on how to handle snapshot versions
