### ISSUE TITLE
split swarm

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [repology/repology-rules#613]
**Source project**

https://repology.org/project/swarm

**Target projects**

1. An open source platform for agent-based models
    http://www.swarm.org/

2. A distributed penetration testing tool
    https://github.com/Arvin-X/swarm

3. Verification script generator for Spin
    http://spinroot.com
    https://github.com/nimble-code/swarm

4. This is SWARM - SoftWare ARM.
    http://www.cl.cam.ac.uk/~mwd24/phd/bin/

5. A robust and fast clustering method for amplicon-based studies
    https://github.com/torognes/swarm

6. Censorship resistant storage and communication infrastructure
    https://github.com/ethersphere/swarm
    https://swarm.ethereum.org

**Comments**
merge https://repology.org/project/go:swarm with 6
move 5 to https://repology.org/project/swarm-cluster

**Comment by Alessandro-Barbieri** [comment]
I see that (4) and (6) are still together

**Comment by AMDmi3** [comment]
Packages which do not have valid homepage information cannot be split.
