### ISSUE TITLE
Redirect OpenBSD fcitx to fcitx5

### ISSUE THREAD

**Issue by ZhanYF** [repology/repology-rules#622]
**Projects affected**

All fcitx packages in OpenBSD's repository are affected.

OpenBSD imports fcitx5-* as fcitx-*, replacing all the old fcitx (4) packages.

Therefore, all fcitx-* packages in OpenBSD's repository are fcitx5 packages, whereas other distros make fcitx (version 4) and fcitx5 co-exist. This causes repology to mistakenly index OpenBSD's fcitx package as fcitx (version 4) packages:
 
https://repology.org/project/fcitx/versions

To correct this, all fcitx packages on OpenBSD's repository should be indexed as fcitx5 packages, including:

fcitx
fcitx-anthy
fcitx-chewing
fcitx-chinese-addons
fcitx-configtool-qt
fcitx-hangul
fcitx-kkc
fcitx-lua
fcitx-m17n
fcitx-qt
fcitx-table-extra
fcitx-unikey

I tried to make a PR myself but can't quite figure out how to write redirect rules :(

**Comment by ZhanYF** [comment]
Got it, it's unlike to be fix on OpenBSD site because this the intended behavior, fcitx4/5 conflict with each other and making them co-exist can be confusing for users.

**Comment by AMDmi3** [comment]
For the record, it has nothing to do with making fctix4/5 coexist, but just a matter of correct naming (e.g. openbsd could just rename fcitx* to fcitx5*).
