### ISSUE TITLE
Go-based debian package versions missing suffix

### ISSUE THREAD

**Issue by AKorezin** [repology/repology-rules#640]
**Projects affected**

Many projects in debian built by go packaging team.
Some of them
- amfora
- cadvisor
- gosu
- prometheus

**Observed behavior**

- package: amfora
  debian: *12*
  package version in repository: *1.9.2-2+b2*
  origversion in repology: *1.9.2-2*
- package: cadvisor
  debian: *11*
  package version in repository: *0.38.7+ds1-2+b7*
  origversion in repology: *0.38.7+ds1-2*
- package: gosu
  debian: *11*
  package version in repository: *1.12-1+b6*
  origversion in repology: *1.12-1*
- package: prometheus
  debian: *11*
  package version in repository: *2.24.1+ds-1+b7*
  origversion in repology: *2.24.1+ds-1*

**Expected behavior**

Origversion in repology should follow the version in repository.

**Comment by AMDmi3** [comment]
```
% curl -s http://ftp.debian.org/debian/dists/bookworm/main/source/Sources.xz | xz -d | grep -A2 Package:\ amfora
Package: amfora
Binary: amfora
Version: 1.9.2-2
```
```
% curl -s http://ftp.debian.org/debian/dists/bullseye/main/source/Sources.xz | xz -d | grep -A2 Package:\ cadvisor
Package: cadvisor
Binary: golang-github-google-cadvisor-dev, cadvisor
Version: 0.38.7+ds1-2
```

**Comment by AKorezin** [comment]
Yeah, but
```
% curl -s http://ftp.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.xz | xz -d | grep -A2 Package:\ cadvisor
Package: cadvisor
Source: cadvisor (0.38.7+ds1-2)
Version: 0.38.7+ds1-2+b7
```

**Comment by AMDmi3** [comment]
Repology uses source package information only.
