### ISSUE TITLE
johntheripper vs. johntheripper-jumbo

### ISSUE THREAD

**Issue by jonasstein** [repology/repology-rules#643]
**Source project**

https://repology.org/project/john/versions

There are two sets in the distributions:

`johntheripper` and `johntheripper-jumbo`

On Gentoo these are called

```
app-crypt/johntheripper
app-crypt/johntheripper-jumbo
```

1. The two flavors `johntheripper` and `johntheripper-jumbo` should be split in two separate packages.
2. The filter has to find out which is the `jumbo` version as the naming scheme is different

you see the other distributions in the list:
https://repology.org/project/john/versions

**Comment by AMDmi3** [comment]
This does not describe what should be done.

**Comment by jonasstein** [comment]
@AMDmi3  OK improved

**Comment by AMDmi3** [comment]
I've left these in a single project, as it's essentially a single project. jumbo versions are treated as devel.
