### ISSUE TITLE
gnutls-guile is being split out from gnutls

### ISSUE THREAD

**Issue by thesamesam** [repology/repology-rules#647]
**Source project**
https://repology.org/project/gnutls

**Target projects**
Need to be split into 'gnutls' and 'gnutls-guile'.

See https://gitlab.com/gnutls/gnutls/-/merge_requests/1651.

**Comments**

Noticed when got a false positive on a new version for gnutls (gnutls 3.7.9 does not yet exist) because Debian is now packaging the split-out guile-gnutls which has a new version: https://packages.debian.org/experimental/source/guile-gnutls.

guile-gnutls is listed at https://repology.org/project/gnutls.

**Comment by AMDmi3** [comment]
Fixed in bfc0d7b8c8e9bc2ae5cd0aa7e68d5b8777090b56
