### ISSUE TITLE
gnutls 3.6.x release should be green

### ISSUE THREAD

**Issue by dg0yt** [repology/repology-rules#660]
**Projects affected**

https://repology.org/project/gnutls/information

**Observed behavior**

Only the highest version (now 3.7.8) is green.
All 3.6.x version are red.

**Expected behavior**

"GnuTLS uses a development cycle where even minor version numbers indicate a stable release and a odd minor version number indicate a development release. " [doc](https://gnutls.org/manual/html_node/Downloading-and-installing.html#Downloading-and-installing). The 3.7 branch aka Next "will be the next stable release; while it is believed to be sufficiently stable it is not as well tested as the stable branch." [downloads](https://gnutls.org/download.html)
So the current release from 3.6.x (now 3.6.16) should be green, too.

**Comment by AMDmi3** [comment]
See #636.
