### ISSUE TITLE
split sci-mathematics/ent

### ISSUE THREAD

**Issue by jonasstein** [repology/repology-rules#673]
**Source project**

Gentoo (and friends) have (a) `sci-mathematics/ent`
which is different from the debian `ent` https://launchpad.net/ubuntu/+source/ent (b)

https://repology.org/project/ent/versions

**Target projects**
a) https://packages.gentoo.org/packages/sci-mathematics/ent
b) https://launchpad.net/ubuntu/+source/ent

**Comment by AMDmi3** [comment]
I don't see how these are different. Both point to https://www.fourmilab.ch/random/

**Comment by jonasstein** [comment]
@AMDmi3 The [1.2debian](https://launchpad.net/ubuntu/+source/ent) versions on the bottom of https://repology.org/project/ent/versions  link to source (b)

**Comment by AMDmi3** [comment]
It's the package source, such link is available for each Ubuntu package. The package is for the same project.

**Comment by jonasstein** [comment]
@AMDmi3 seems I really got confused. My fault. Closing.
