### ISSUE TITLE
How to have repology single project API returns the right result?

### ISSUE THREAD

**Issue by chenrui333** [repology/repology-rules#678]
Currently when I am doing something like this, I got no results

```
$ curl https://repology.org/api/v1/project/fd?inrepo=homebrew
[]
```

That is due to the fact the package set is called `fd-find`, so if I update to use `fd-find` I would get success

```
$ curl https://repology.org/api/v1/project/fd-find?inrepo=homebrew
[{"repo":"gnuguix","srcname":"fd","binname":"fd",
....
```

What is the best way to overcome this situation? Thanks!!

**Comment by AMDmi3** [comment]
https://repology.org/tools/project-by
