### ISSUE TITLE
T2 SDE qmail says "150", makes no sense

### ISSUE THREAD

**Issue by schmonz** [repology/repology-rules#683]
I'm maintainer for qmail in pkgsrc. The last upstream release by DJB was 1.03. (I'm also cofounder of [notqmail](https://github.com/notqmail/notqmail), a community-developed open source fork.)

Recently T2 SDE started numbering [their qmail package](http://t2sde.org/packages/qmail) strangely, making all the other packages report as outdated. (Insert joke here about how anyone still using qmail in 2023 is outdated ;-)

Please ignore T2 SDE's versioning of qmail. Thanks!

**Comment by schmonz** [comment]
Solved by [3d2bfd4](https://github.com/repology/repology-rules/commit/3d2bfd4b6680b017c7d0abb495e5866234dda87c). Thanks!

**Comment by AMDmi3** [comment]
Yep, T2 was completely blacklisted, thanks for report!
