### ISSUE TITLE
cachelib issues

### ISSUE THREAD

**Issue by dg0yt** [repology/repology-rules#684]
**Projects affected**

There is `cachelib` and there is `python:cachelib`.
https://repology.org/projects/?search=cachelib

**Observed behavior**

`cachelib` lists a facebook lib, from Fedora. But this version is ignored.
`cachelib` lists eight versions which seem to belong to `python:cachelib`, and the repositories are not listed in `python:cachelib`:
Debian, Kali, Raspian, Ubuntu.

**Expected behavior**

`cachelib` lists only ports of the facebook lib.
The Debian, Kali, Raspian, Ubuntu versions are listed with `python:cachelib` (if this is where they belong).

---

Context: There is PR to add a facebook cachelib port to vcpkg.

**Comment by dg0yt** [comment]
Do you plan to leave the Debian and Ubuntu variants as "unclassified"?  AFAICS they build python package (e.g. https://packages.ubuntu.com/source/jammy/cachelib), and they might be "classified" via the "Upstream homepage" (https://github.com/pallets-eco/cachelib) which is known from python:cachelib.

**Comment by AMDmi3** [comment]
> Do you plan to leave the Debian and Ubuntu variants as "unclassified"?

Yes, for the same reason I don't support merge rules for unprefixed python modules.
