### ISSUE TITLE
crates.io project missing despite same name

### ISSUE THREAD

**Issue by michidk** [repology/repology-rules#688]
Hello, this is my first interaction with this projects - so I am not quite sure this is the right place to report such issue. But basically there is an issue with the data that the repology website shows.

**Projects affected**

https://repology.org/project/punktf/versions

**Observed behavior**

The crate `punktf` is not listed, despite being on crates.io: https://crates.io/crates/punktf

![](https://repology.org/badge/vertical-allrepos/punktf.svg)

**Expected behavior**

The crate `punktf` should be listed.

**Comment by AMDmi3** [comment]
All projects from module collections (crates, pypi, rubygems, cpan etc.) go into their own namespaces, so the crate gets into `rust:punktf`. These are hidden from normal search, but can be discovered through the [Related](https://repology.org/project/punktf/related) tab. The projects which are actually end-user applications and not a libraries, manual mere rules need to be added.
