### ISSUE TITLE
map pkgsrc's versioning of ucspi-ssl

### ISSUE THREAD

**Issue by schmonz** [repology/repology-rules#691]
**Projects affected**

The newest release of [ucspi-ssl](https://www.fehcom.de/ipnet/ucspi-ssl.html) is currently 0.12.6.

pkgsrc contains this latest version, but with version number 0.999.12.6. We've been renumbering ucspi-ssl versions in this way (replacing `^0\.` with `0.999.`) since 2018Q3.

Why do we do this? Short answer: because otherwise it won't sort newer than all previous versions.

Longer answer:
- In 2018Q2, the upstream maintainer published what turned out to be the last version under the existing versioning scheme, which had been proceeding like this: 0.70 -> 0.99 -> 0.99b -> 0.99d -> 0.99e (all clearly newer than the previous).
- In Q3, he published 0.10.6, which by most comparisons doesn't look "newer" at all. I was not able to persuade him to choose a different scheme.
- So when I updated pkgsrc's ucspi-ssl to 0.10.6, I took matters into my own hands and called it "0.999.10.6", so that it would sort newer than what we'd had before. And I've stuck with that pattern ever since.

**Observed behavior**

pkgsrc's ucspi-ssl version is ignored, so it never shows up in my maintainer report, even when it needs an update.

**Expected behavior**

pkgsrc's ucspi-ssl versioning scheme is mapped onto the (current) upstream versioning scheme, so Repology can know when it's up-to-date or not.

I maintain over 100 packages and it would be a lot harder to stay on top of things without Repology. Thank you for providing it!

**Comment by AMDmi3** [comment]
Repology does not honor fake versions and especially doesn't fix them.

> because otherwise it won't sort newer than all previous versions

pkgsrc should have mechanism similar to FreeBSD's `PORTEPOCH` to handle such cases.

**Comment by schmonz** [comment]
I'm disappointed. I imagine you have many goals with Repology, and that sometimes they're at odds; I hadn't imagined that supporting maintainers keeping packages up-to-date -- even when that means adding a small programmatic rule when upstream versioning has gone wackadoodle -- would be a lower priority than this one, whatever you'd call it. I wouldn't call it "representing reality usefully" because you're explicitly choosing for your system not to accurately model a very real state.

I appreciate your suggestion that this could be solved by the addition of some infrastructure in pkgsrc, and agree that that would be true. I hope decisions like this do actually help you keep the cost of Repology maintenance down, because otherwise from the outside they don't appear to serve anyone's needs.
