### ISSUE TITLE
Rizin, Radare2, Cutter

### ISSUE THREAD

**Issue by XVilka** [repology/repology-rules#700]
**Projects affected**

- https://repology.org/project/radare2-cutter/versions
- https://repology.org/project/cutter-unclassified/versions

**Observed behavior**

Name of the project doesn't reflect the current situation

**Expected behavior**

Since Cutter 2.x versions it switched from Radare2 to Rizin as a backend (a fork of Radare2). Meanwhile, Radare2 developers renamed their GUI to "Iaito": 

1. "radare2-cutter" should become just "cutter-re", like it's already called in some distributions (Fedora)
2. "cutter-unclassified" that currently contains packages for Nix, should also become part of this category

Some of the packages called "radare2-cutter", right, but with time they will either update to Rizin-based Cutter, or Radare2-based Iaito (https://repology.org/project/iaito/versions), thus the name is misleading from the point of view of both projects.

**Links for the reference**

- https://cutter.re
- https://github.com/rizinorg/cutter
- https://rizin.re/posts/faq/
- https://github.com/radareorg/iaito

**Comment by XVilka** [comment]
@AMDmi3 there is one that new rules missed: https://repology.org/project/cutter-unclassified/versions:


AOSC | cutter | 2.1.0 | devel | fallback-mnt-aosc@repology
-- | -- | -- | -- | --


[AOSC](https://repology.org/repository/aosc)	[cutter](https://packages.aosc.io/packages/cutter)	[2.1.0](https://packages.aosc.io/packages/cutter)	devel	[fallback-mnt-aosc@repology](https://repology.org/maintainer/fallback-mnt-aosc@repology)

**Comment by AMDmi3** [comment]
This is as expected, it doesn't have WWW data and cannot be classified
