### ISSUE TITLE
NodeJS - Reflect several LTS Releases

### ISSUE THREAD

**Issue by VlkrS** [repology/repology-rules#712]
**Projects affected**
[nodejs](https://repology.org/project/nodejs/versions)

**Observed behavior**
The 18.x version family is shown to be outdated

**Expected behavior**
NodeJS 18.x is the currently recommended LTS release line and should not yet appear to be 'outdated'.
According to https://github.com/nodejs/release#release-schedule, it should probably move to 'legacy' in October 2023

**Comment by AMDmi3** [comment]
Repology does not provide any special handling for LTS releases. However, as long as latest version is provided by a repository, older version may be marked as legacy instead of outdated there.
