### ISSUE TITLE
more adacore crap

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-rules#713]
**Projects affected**
A subset of adacore projects

currently:
https://repology.org/project/ada-language-server/versions
https://repology.org/project/ada-markdown/versions
https://repology.org/project/ada-spawn/versions
https://repology.org/project/templates-parser/versions
https://repology.org/project/gnatcoll-bindings/versions
https://repology.org/project/gnatcoll-core/versions
https://repology.org/project/gnatdoc/versions
https://repology.org/project/gpr/versions
https://repology.org/project/gprbuild/versions
https://repology.org/project/gtkada/versions
https://repology.org/project/libadalang/versions
https://repology.org/project/libadalang-tools/versions
https://repology.org/project/vss/versions
https://repology.org/project/xmlada/versions

**Observed behavior**
So Adacore has been famous for varying version format for years, but recently seems to have converged on YY.a.b, e.g. "23.0.0" for the first release of 2023.   But development releases used to add "w".   I think it stands for "working".   So Rod M at AUR has been importing all these development versions that's bumping the release, e.g.
![image](https://github.com/repology/repology-rules/assets/1125622/c2ca3257-1c26-469c-83a4-1da396285b93)

**Expected behavior**
I expect a rule to be developed that any version ending in "w" be considered "devel" and not a release.
So all these in the screenshot would have not superceded the 23.0.0 release.
If the version was "24.0.0" rather than "24.0w" then of course that should considered a release.
releases should also have 3 components ("24", "0", "0") whereas "24.0w" only has 2 components.

**Comment by AMDmi3** [comment]
Patch is welcome. That would be 
```
- { name: XXX, verpat: ".*w", devel: true }
```
for each of these.

**Comment by jrmarino** [comment]
thanks.  I'll get a PR in soon.
