### ISSUE TITLE
The "dnf" project is shown with a wrong latest version due to the collision of Wikidata records

### ISSUE THREAD

**Issue by yurivict** [repology/repology-rules#728]
**Projects affected**
[dnf](https://repology.org/project/dnf/versions)

**Observed behavior**
Repology shows the latest version for the project "dnf" as 5.0.15.
In fact this project was renamed and is now continuing as "dnf5". The old "dnf" project has the version 4.16.1
Maybe one Wikidata record is for "dnf" and another one is for "dnf5", but they both are shown on the "dnf" project's page.

**Comment by AMDmi3** [comment]
You can fix wikidata
