### ISSUE TITLE
CFlow naming conflict

### ISSUE THREAD

**Issue by awilfox** [repology/repology-rules#74]
As seen on [Repology's cflow page](https://repology.org/metapackage/cflow/versions), FreeBSD and DPorts [ship "2.0"](https://www.freshports.org/devel/cflow) while the rest have 1.4/1.5.

All 1.x versions correspond to [GNU CFlow](https://www.gnu.org/software/cflow/).  FreeBSD's cflow-2.0 was released in 1995, about 10 years before GNU's existed.

The problem is I don't know what the FreeBSD CFlow package's proper name would be.  It isn't bsdcflow, as that already exists.

**Comment by AMDmi3** [comment]
There are 3 cflow variants. This should fix it.
