### ISSUE TITLE
MATE development branches

### ISSUE THREAD

**Issue by lexeii** [repology/repology-rules#75]
There are already some metapackages that simultaneously have both stable and development branches for which the choice is based only on the version number:

  * [darktable](https://repology.org/metapackage/darktable/versions): 2.4.* is stable, 2.5.* is development
  * [libreoffice](https://repology.org/metapackage/libreoffice/versions): 6.0.* is stable, 6.1.* is development
  * and so on

It would be very great if this behavior will also be propagated to the packages of the MATE project: even versions are stable (currently [1.20](http://pub.mate-desktop.org/releases/1.20/)) while odd - are development (currently [1.21](http://pub.mate-desktop.org/releases/1.21/)). Here MATE [blog](http://mate-desktop.org/blog/) with release announcements.

Affected packages:

  - [x] [atril](https://repology.org/metapackage/atril/versions)
  - [x] [caja](https://repology.org/metapackage/caja/versions)
  - [x] [caja-dropbox](https://repology.org/metapackage/caja/versions) (absent in 1.21)
  - [x] [caja-extensions](https://repology.org/metapackage/caja-extensions/versions) (absent in 1.21)
  - [x] [engrampa](https://repology.org/metapackage/engrampa/versions)
  - [x] [eom](https://repology.org/metapackage/eom/versions)
  - [x] [libmatekbd](https://repology.org/metapackage/libmatekbd/versions)
  - [x] [libmatemixer](https://repology.org/metapackage/libmatemixer/versions)
  - [x] [libmateweather](https://repology.org/metapackage/libmateweather/versions)
  - [x] [marco](https://repology.org/metapackage/marco/versions)
  - [x] [mate-applets](https://repology.org/metapackage/mate-applets/versions)
  - [x] [mate-backgrounds](https://repology.org/metapackage/mate-backgrounds/versions) (absent in 1.21)
  - [x] [mate-calc](https://repology.org/metapackage/mate-calc/versions)
  - [x] [mate-common](https://repology.org/metapackage/mate-common/versions) (absent in 1.21)
  - [x] [mate-control-center](https://repology.org/metapackage/mate-control-center/versions)
  - [x] [mate-desktop](https://repology.org/metapackage/mate-desktop/versions) **(this one really know about stable and dev!)**
  - [x] [mate-icon-theme](https://repology.org/metapackage/mate-icon-theme/versions)
  - [x] [mate-icon-theme-faenza](https://repology.org/metapackage/mate-icon-theme-faenza/versions) (absent in 1.21)
  - [x] [mate-indicator-applet](https://repology.org/metapackage/mate-indicator-applet/versions) (absent in 1.21)
  - [x] [mate-media](https://repology.org/metapackage/mate-media/versions)
  - [x] [mate-menus](https://repology.org/metapackage/mate-menus/versions)
  - [x] [mate-netbook](https://repology.org/metapackage/mate-netbook/versions) (absent in 1.21)
  - [x] [mate-notification-daemon](https://repology.org/metapackage/mate-notification-daemon/versions)
  - [x] [mate-panel](https://repology.org/metapackage/mate-panel/versions)
  - [x] [mate-polkit](https://repology.org/metapackage/mate-polkit/versions) (absent in 1.21)
  - [x] [mate-power-manager](https://repology.org/metapackage/mate-power-manager/versions)
  - [x] [mate-screensaver](https://repology.org/metapackage/mate-screensaver/versions)
  - [x] [mate-sensors-applet](https://repology.org/metapackage/mate-sensors-applet/versions)
  - [x] [mate-session-manager](https://repology.org/metapackage/mate-session-manager/versions)
  - [x] [mate-settings-daemon](https://repology.org/metapackage/mate-settings-daemon/versions)
  - [x] [mate-system-monitor](https://repology.org/metapackage/mate-system-monitor/versions)
  - [x] [mate-terminal](https://repology.org/metapackage/mate-terminal/versions)
  - [x] [mate-user-guide](https://repology.org/metapackage/mate-user-guide/versions)
  - [x] [mate-user-share](https://repology.org/metapackage/mate-user-share/versions) (absent in 1.21)
  - [x] [mate-utils](https://repology.org/metapackage/mate-utils/versions)
  - [x] [mozo](https://repology.org/metapackage/mozo/versions)
  - [x] [pluma](https://repology.org/metapackage/pluma/versions)
  - [x] [python-caja](https://repology.org/metapackage/python:caja/versions) (absent in 1.21)

**Comment by AMDmi3** [comment]
Starting with unchecking everything, as despite there's no devel version currently, rules still need to be added. Also a lot of projects require merging. Note that I'm not merging anything from SliTaz, as its splits will be hopefully fixed by a new repo information dump.
