### ISSUE TITLE
KDE's 6th Megarelease - Alpha

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-rules#761]
3 dozen + KDE framework ports
e.g.
kf5-attica
kf5-kwidgetsaddons
kf5-kcodecs
kf5-karchive
kf5-kded
kf5-kglobalaccel
kf5-kdoctools
kf5-kwindowsystem
kf5-kcompletion
kf5-kservice
kf5-kconfig
kf5-extra-cmake-modules
kf5-kauth
kf5-kjobwidgets
kf5-kdbusaddons
kf5-ki18n
kf5-breeze-icons
kf5-kitemviews
kf5-sonnet
kf5-kcoreaddons
kf5-kcrash
kf5-solid

It was reported before but the latest release of KDE framework 5 is 
5.113.0

The the releases like 5.246.0, 5.247.0 are alpha releases for KDE framework 6:
https://kde.org/announcements/megarelease/6/alpha/

Hopefully there is some kind of rule that can be generated to identify these alpha releases because just about all kf5 projects are misidentified right now

**Comment by AMDmi3** [comment]
Redirecting related reports here.

extra-cmake-modules

> 5.245.0 and 5.246.0 are unstable releases as seen in upload path:
> - https://download.kde.org/unstable/frameworks/5.246.0/extra-cmake-modules-5.246.1.tar.xz
> - https://download.kde.org/unstable/frameworks/5.245.0/extra-cmake-modules-5.245.0.tar.xz
> 
> And they are part of KDE beta:
> - https://kde.org/announcements/megarelease/6/beta1/
> - https://kde.org/info/kde-frameworks-5.246.0/
> 
> Stable releases are uploaded under https://download.kde.org/stable/frameworks/ 

angelfish

> 24.01.xx are all alpha/beta/rc releases for KDE Apps, latest stable is 23.08.3, this counts for all listed on repology as 24.01.xx:
> https://community.kde.org/Schedules/February_2024_MegaRelease
> https://github.com/ScoopInstaller/GithubActions/pull/38#issuecomment-1850544901

flatpak-kcm

> 5.27.80 (soon to be .90) are all alpha/beta/rc releases for KDE Plasma 6, latest stable is 5.27.9, this counts for all listed on repology as 5.27.80:
> https://community.kde.org/Schedules/February_2024_MegaRelease 

attica

> Latest unstable Frameworks is 5.246.0:
> https://download.kde.org/unstable/frameworks/
> So, makes no sense to list 5.245.0 as latest stable (which it is not, stable is 5.113.0), and set 5.246.0 as untrusted. 

kauth

> A lot of kframeworks packages need version ignore since versions 2.245.0+ are considered to be BETA. https://packages.gentoo.org/packages/kde-frameworks/kauth
> Relevant to karchive, kauth, kcodecs, kconfig, kcoreaddons, kguiaddons, ki18n, kirigami, kitemmodels, kitemviews, kwidgetsaddons, kwindowsystem and others.

**Comment by AMDmi3** [comment]
Fixed by KDE 6 release. Some merges are probably required now, though.
