### ISSUE TITLE
wireless-tools is still showing incorrect versions

### ISSUE THREAD

**Issue by awilfox** [repology/repology-rules#78]
[Currently](https://repology.org/metapackage/wireless-tools/versions), wireless-tools is showing that 30 is the current version, despite the fact that e316df7a was supposed to fix this so that 30_pre9 is the actually correct current version.

![screenshot_20180909_140636](https://user-images.githubusercontent.com/303838/45267839-8c9c7700-b439-11e8-9632-38f5763deef4.png)

**Comment by AMDmi3** [comment]
This is not correct. Underscore may not appear in the rules ≥ 800 ruleset since it's normalized in 799. The cause is the new repo shipping wireless-tools 30, I  think it's pld.
