### ISSUE TITLE
Better handling of ncurses versioning?

### ISSUE THREAD

**Issue by jon-turney** [repology/repology-rules#780]
Looking at the list of versions on https://repology.org/project/ncurses/information is not as helpful as it might be.

I'm told that upstream releases e.g. 6.4 and then a sequence of 6.4-YYYYMMDD "snapshots". These are the things that everyone is packaging. Unfortunately, distro handling of these is inconsistent, which is perhaps not helped by the '-' character not being allowed in versions in some (many?) places.

I think maybe a rule transforming (\d+)\.(\d+)[_-+]p?(\d+) to \1.\2.\3 or something like that might be appropriate?

**Observed behavior**

Repology tells me that 6.4 is the latest version

**Expected behavior**

Repology tells me that (currently) 6.4.20240127 is the latest version

**Comment by AMDmi3** [comment]
> I'm told that upstream releases e.g. 6.4 and then a sequence of 6.4-YYYYMMDD "snapshots". These are the things that everyone is packaging.

Everyone is most likely packaging 6.4 which is the official [latest stable version](https://invisible-island.net/ncurses/ncurses.faq.html#latest_version).

> Unfortunately, distro handling of these is inconsistent, which is perhaps not helped by the '-' character not being allowed in versions in some (many?) places

There's no problem here as repology treats `6.4.20240127`, `6.4-20240127`, `6.4_20240127` and `6.4+20240127` equally.

> Repology tells me that (currently) 6.4.20240127 is the latest version

That's would not be correct. However it makes sense to treat 3-component versions as devel.
