### ISSUE TITLE
fix some missing quotes

### ISSUE THREAD

**Issue by peutch** [repology/repology-rules#783]
Hi,
And here is a patch.
Thanks!

[repology-rules_patch.txt](https://github.com/repology/repology-rules/files/14319627/repology-rules_patch.txt)

**Comment by AMDmi3** [comment]
1. Please submit changes as pull requests
2. The quotes you refer to as missing are not needed at all

**Comment by peutch** [comment]
Sorry, I was not sure about this regarding the fact that the quotes were sometimes there and (few) times not, that is why I did not open a PR. But sure now I will move away from Java YamlBeans!
