### ISSUE TITLE
KDE development branches

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-rules#79]
Odd minor version should be marked as devel. See

- https://download.kde.org/stable/applications/
- https://download.kde.org/unstable/applications/ 

---

- [x] akonadi
- [x] akonadi-calendar
- [x] akonadi-calendar-tools
- [x] akonadi-contacts
- [x] akonadi-import-wizard
- [x] akonadi-mime
- [x] akonadi-notes
- [x] akonadi-search
- [x] akonadiconsole
- [x] akregator
- [x] analitza
- [x] ark
- [x] artikulate
- [x] audiocd-kio
- [x] baloo-widgets
- [x] blinken
- [x] bovo
- [x] calendarsupport
- [x] cantor
- [x] cervisia
- [x] dolphin
- [x] dolphin-plugins
- [x] dragon-player
- [x] eventviews
- [x] ffmpegthumbs
- [x] filelight
- [x] granatier
- [x] grantlee-editor
- [x] grantleetheme
- [x] gwenview
- [x] incidenceeditor
- [x] juk
- [x] k3b
- [x] kaccounts-integration
- [x] kaccounts-providers
- [x] kaddressbook
- [x] kalarm
- [x] kalarmcal
- [x] kalgebra
- [x] kalzium
- [x] kanagram
- [x] kapptemplate
- [x] kate
- [x] kbounce
- [x] kbruch
- [x] kcachegrind
- [x] kcalc
- [x] kcalcore
- [x] kcalutils
- [x] kcharselect
- [x] kcolorchooser
- [x] kcontacts
- [x] kcron
- [x] kdav
- [ ] ~kde-common~ (no such thing)
- [x] kdebugsettings
- [x] kdeedu-data
- [x] kdegraphics-mobipocket
- [x] kdegraphics-thumbnailers
- [x] kdenetwork-filesharing
- [x] kdenlive
- [x] kdepim-addons
- [x] kdepim-apps-libs
- [x] kdepim-runtime
- [x] kdesdk-kioslaves
- [x] kdesdk-thumbnailers
- [x] kdialog
- [x] keditbookmarks
- [x] kfind
- [x] kfourinline
- [x] kgeography
- [x] kget
- [x] kgpg
- [x] khangman
- [x] khelpcenter
- [x] kidentitymanagement
- [x] kig
- [x] kimap
- [x] kio-extras
- [x] kiriki
- [x] kiten
- [x] kldap
- [x] kleopatra
- [x] klettres
- [x] kmag
- [x] kmahjongg
- [x] kmail
- [x] kmail-account-wizard
- [x] kmailtransport
- [x] kmbox
- [x] kmime
- [x] kmines
- [x] kmix
- [x] kmouth
- [x] kmplot
- [x] knavalbattle
- [x] knotes
- [x] kolourpaint
- [x] kompare
- [x] konqueror
- [x] konquest
- [x] konsole
- [x] kontact
- [x] kontactinterface
- [x] kopete
- [x] korganizer
- [x] kpat
- [x] kpimtextedit
- [x] krdc
- [x] krfb
- [x] kruler
- [x] kshisen
- [x] ksmtp
- [x] ksystemlog
- [x] kteatime
- [x] ktimer
- [x] ktnef
- [x] ktouch
- [x] ktuberling
- [x] kturtle
- [x] kwalletmanager
- [x] kwave
- [x] kwordquiz
- [x] libgravatar
- [x] libkcddb
- [x] libkdcraw
- [x] libkdegames
- [x] libkdepim
- [x] libkeduvocdocument
- [x] libkexiv2
- [x] libkgapi
- [x] libkipi
- [x] libkleo
- [x] libkmahjongg
- [x] libkomparediff2
- [x] libksane
- [x] libksieve
- [x] lokalize
- [x] mailcommon
- [x] mailimporter
- [x] marble
- [x] messagelib
- [x] okular
- [x] parley
- [x] pimcommon
- [x] print-manager
- [x] rocs
- [x] signon-kwallet-extension
- [x] spectacle
- [x] step
- [x] sweeper
- [x] umbrello

**Comment by awilfox** [comment]
Some packages were missed, mostly the KDE Games collection, and I'm seeing 18.11.80 as "current" due to OpenMandriva Cooker:

bomber
kapman
katomic
kblackbox
kblocks
kbreakout
kdf
kdiamond
kfloppy
kgoldrunner
killbots
kjumpingcube
klickety
klines
kmousetool
knetwalk
kolf
kollision
kreversi
ksirk
ksnakeduel
kspaceduel
ksquares
ksudoku
kubrick
lskat
minuet
palapeli

**Comment by awilfox** [comment]
I've just added rules for all of the above in #107.
