### ISSUE TITLE
Remove warning for Npackd repositories 2

### ISSUE THREAD

**Issue by tim-lebedkov** [repology/repology-rules#808]
**Projects affected**
https://repology.org/repository/npackd_stable
https://repology.org/repository/npackd_stable64
https://repology.org/repository/npackd_unstable

**Observed behavior**
Repology shows this warning:

This repository [does not provide](https://repology.org/repositories/fields#npackd_stable) links to package recipes or sources in a way accessible by Repology. This is critical, because one of the goals of Repology is to make the details of how a project is packaged visible to anyone. It makes Repology maintenance harder as it's not possible to easily check where a specific version comes from; it does not allow upstream to check the recipe and improve their software to simplify packaging, or suggest corrections to the maintainer; it does not allow other maintainers to learn new ideas. It may be as well dangerous to users due to lack of transparency. Because of that, this repository is subject to removal in the near future.

See [documentation](https://repology.org/addrepo) for a best way to make package metadata available for Repology.

**Expected behavior**

No warning. The recipes are open source under GPLv3. #779 was just closed without a resolution. I would like this warning to be removed. What would be an acceptable solution?

**Comment by AMDmi3** [comment]
Duplicate
