### ISSUE TITLE
Special case - Needs help to create rules for hardinfo2

### ISSUE THREAD

**Issue by hwspeedy** [repology/repology-rules#824]
Hi @AMDmi3, thanx for a great tool!  - CC: hardinfo2 debian/ubuntu package maintainer @hosiet

We have a special corner case and could use some help from you.

hardinfo is rebootet as hardinfo2 after >10 years without releases. 
The domain+github was used other private stuff, so we could not continue hardinfo but had to move to **hardinfo2** - https://www.hardinfo2.org

Debian/Ubuntu++ branch had the old hardinfo package and therefor to support users in the best way, the source package is released with the continuing name hardinfo in that branch - the binary packages are hardinfo+hardinfo2. (@hosiet is WIP on upgrading distros with the bugfixed edition for maintained distros)
Note: https://tracker.debian.org/pkg/hardinfo2 - redirects to hardinfo

**Is it possible to add hardinfo packages with version >=2. to hardinfo2 badge?**
It is okay to leave info for hardinfo package as is or should they just be merged? @hosiet @AMDmi3 

**Feature request:**
switch for svg badges to remove unofficial channels like RPM Sphere 
- The "exclude_sources=RPM+Sphere" does not work...

switch for svg badges to remove all too old packages - version below a defined version number.
The minversion is for red/green coloring - a minversionshown would be great.

**It is such a great way to show and check up on packaging in all distros, thanx.**

**hardinfo2 github page with packaging badge:** - https://github.com/hardinfo2/hardinfo2/
[![Packaging status](https://repology.org/badge/vertical-allrepos/hardinfo2.svg?columns=3&exclude_sources=RPM+Sphere&exclude_unsupported=1)](https://repology.org/project/hardinfo2/versions)

**The OLD hardinfo program:**
[![Packaging status](https://repology.org/badge/vertical-allrepos/hardinfo.svg?columns=3&exclude_unsupported=1)](https://repology.org/project/hardinfo/versions)

NOTE: The Debian hardinfo package is a transitional package and will probably disappear over time...

In advance thanx,

/hwspeedy

**Comment by AMDmi3** [comment]
I'd just merge both hardinfo and hardinfo2 into single project. If hardinfo2 is a continuation of hardinfo, I see no reason to track projects separately, and this makes it apparent which repositories need an update.

There already are switches to exclude EOLed repos and also non repositories like freshcode and wikidata, these are documented on [badges](https://repology.org/project/hardinfo2/badges) page. I don't want to allow excluding specific kinds of repositories as it breaks providing a complete picture of projects packaging.

**Comment by hwspeedy** [comment]
Sounds fine with a merge.

Please consider the github badge is mostly the project maintainers view of updating process.
