### ISSUE TITLE
Problems with splitting sushi

### ISSUE THREAD

**Issue by City-busz** [repology/repology-rules#856]
The split between gnome-sushi and sushi-unclassified does not work well:
https://repology.org/project/gnome-sushi/versions
https://repology.org/project/sushi-unclassified/versions

Most of the packages listed on sushi-unclassified should be in gnome-sushi instead.

**Comment by AMDmi3** [comment]
This is as intended. Packages should have valid upstream URLs to be classified properly. What's left in sushi-unclassified provides dead, unrelated or redirecting URLs.

**Comment by City-busz** [comment]
I don't think so. If you check the homepage links on sushi-unclassified, most of them points to gnome-sushi, which shouldn't be listed there:
 https://repology.org/project/sushi-unclassified/information#Homepage_links

**Comment by AMDmi3** [comment]
> What's left in sushi-unclassified provides dead, unrelated or redirecting URLs.
