### ISSUE TITLE
go:uuid differentiate a package

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#86]
https://repology.org/metapackage/go:uuid/versions

https://github.com/google/uuid/releases vs https://github.com/satori/go.uuid/releases

**Comment by blshkv** [comment]
hm.. let me try to rename it in Pentoo first.

**Comment by blshkv** [comment]
That did not help. The issue seems still valid. Back to you..

**Comment by AMDmi3** [comment]
It's quite a mess, go does seem to discourage unique package naming. First thing to do here is to add a wildcard rule which adds `go:` prefix to Gentoo packages in `app-go` category, but this still won't fix the problem, as `go:uuid` is inevitably ambiguous. For instance, there are these packages which intersect or may intersect with it:

- go:github-google-uuid
- go:github-hashicorp-go-uuid
- go:github-hashicorp-uuid
- go:github-nu7hatch-gouuid
- go:github-pborman-uuid
- go:github-satori-go.uuid
- go:github-satori-uuid
- go:github-twinj-uuid
- go:googlecode-uuid

So one solution I see is for pentoo to adopt `github-XXX-YYY` naming scheme. It's not widely used in Gentoo/derivatives yet, but given that many distros have already adopted it ([example](https://repology.org/metapackage/go:github-shurcool-sanitized-anchor-name/versions)), this solution may be viable. Another solution is for pentoo to publish more detailed package metadata dumps so I could disambiguate packages using homepage urls.

**Comment by blshkv** [comment]
We do publish this information, see ```EGO_PN=github.com/google/uuid``` or you can grab it from SRC_URI (more standard).
https://github.com/pentoo/pentoo-overlay/blob/master/dev-go/uuid/uuid-1.0.0.ebuild#L6

The same information can be also available via metadata.xml but this is less common or/and optional.

I could use something like ```dev-go/uuid-google``` but there is no standard rule for Gentoo as far as I know, so it would be to a very reliable sources

Do let me know what else can be improved.

**Comment by AMDmi3** [comment]
> We do publish this information

Repology doesn't parse ebuilds. For gentoo it uses directory structure, metadata.xml and metadata/md5cache/*. For Pentoo, only directory structure is available, which only contains cagetory, name and version.

> I could use something like dev-go/uuid-google but there is no standard rule for Gentoo as far as I know, so it would be to a very reliable sources

No, there's no point introducing _yet another_ name. It should either be `dev-go/uuid` with data enough to distinguish it from other projects, or `dev-go/github-google-uuid`

**Comment by blshkv** [comment]
Personally, I feel ```github``` is an overkill in the name, the package's author is enough. Funny enough, I have not found any non-github hosted go package.

Btw, I found the first similar case in Gentoo tree as well:
dev-go/gogo-protobuf  (github.com/gogo/protobuf)
dev-go/go-protobuf (github.com/golang/protobuf)

Perhaps, it should be ```dev-go/golang-protobuf``` in the last case

https://github.com/gentoo/gentoo/tree/master/dev-go/go-protobuf

https://github.com/gentoo/gentoo/commits?author=hanetzer 
https://github.com/gentoo/gentoo/commits?author=zmedico
To: @hanetzer @zmedico  would be good if you could comment.

**Comment by hanetzer** [comment]
@blshkv Honestly I have little to no idea what would be good here. I don't use go personally
and have little to no knowledge about its infrastructure/ecosystem other than it does a lot of
package management in and of itself and tends to centralize around github.

**Comment by blshkv** [comment]
@hanetzer @zmedico sorry for adding you to the list, I have seen you have commited the go ebuild and might have some ideas.  We are trying to sort out go mess and come up with a feasible name scheme.

As you can see, there are multiple ```uuid``` go projects in this case, similar to protobuf.

So the proposed way is to use ```<host>-<author>-<package>```.ebuild or ```<author>-<package>.ebuild```. I would really appreciate your input.

**Comment by hanetzer** [comment]
@blshkv np. the commit was just a general ebuild style/housecleaning commit, nothing
of substance. I tend to grab a category of packages with a fair amount of fixes of that sort
and do them in large swaths, even if I don't use the package myself. Unwatching this, but
glad to see I'm visible :+1:

**Comment by blshkv** [comment]
> > 
> 
> Repology doesn't parse ebuilds. For gentoo it uses directory structure, metadata.xml and metadata/md5cache/*. For Pentoo, only directory structure is available, which only contains cagetory, name and version.

Can you please add metadata.xml parsing for overlays as well? It should benefit other packages (mostly forks) such as 
```
dev-libs/openssl-bad
dev-libs/openssl-chacha

net-wireless/rtl8812au_aircrack-ng
net-wireless/rtl8812au_astsam
net-wireless/rtl8812au_asus
```

There is no strict rule how to name ebuilds in Gentoo and <upstream> entry would help to map it

**Comment by AMDmi3** [comment]
> Can you please add metadata.xml parsing for overlays as well?

It's already enabled for everything which uses Gentoo parser.

> It should benefit other packages (mostly forks) such as

It will not benefit forks, as homepage urls are only useful and used for splitting. Forks require manual merge rules.

What's left now is to

> add a wildcard rule which adds `go:` prefix to Gentoo packages in app-go category

and I'm currently working on that. Afterwards, google and satori "go:uuid", could be split as homepage urls are already available.

**Comment by blshkv** [comment]
Great, thank you!
