### ISSUE TITLE
Consider normalizing all YAML files

### ISSUE THREAD

**Issue by txtsd** [repology/repology-rules#877]
Consider formatting and normalizing all YAML files with something like [ruamel.yaml](https://pypi.org/project/ruamel.yaml/).

If you're interested, I can dive deeper and submit a draft PR.

**Comment by AMDmi3** [comment]
For what purpose? Please give an example.

**Comment by txtsd** [comment]
Line endings, Newline at EOF, prune trailing spaces, aligning columns with `ruamel.yaml`'s round-trip feature, add 2 spaces before in-line comments, general linting and formatting.
