### ISSUE TITLE
nixpkgs: tcl packages are not detected

### ISSUE THREAD

**Issue by fgaz** [repology/repology-rules#878]
**Projects affected**

All Tcl packages. Example: https://repology.org/project/tcllib/

**Observed behavior**

Since https://github.com/NixOS/nixpkgs/pull/344716 all [Tcl packages from nixpkgs](https://search.nixos.org/packages?channel=unstable&query=tclPackages) disappeared from repology.

**Expected behavior**

Tcl packages such as `tcllib` should have a nixpkgs unstable entry, possibly under a `tcl:` namespace.

**Comment by AMDmi3** [comment]
These are [here](https://repology.org/projects/?search=&maintainer=&category=tclPackages&inrepo=nix_unstable). See [835](https://github.com/repology/repology-rules/pull/835#issuecomment-2278559850).
