### ISSUE TITLE
openbsd: snapshot version comparison 

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#88]
https://repology.org/metapackage/ike-scan/versions
this may be a long pending issue:
https://github.com/repology/repology/issues/345

```
OpenBSD Ports | ike-scan | 1.9.4pl20170804
vs
Gentoo overlay Pentoo | ike-scan | 1.9.4_p20170805
```

somehow, openbsd's version has a higher priority and list others as outdated

**Comment by blshkv** [comment]
btw, the same package shown as:
1.9.4 (outdated)	1.9.4_p20170805 (legacy)
at the following URL: https://repology.org/metapackages/?inrepo=gentoo_ovl_pentoo&outdated=1

**Comment by AMDmi3** [comment]
It's all correct, because `p` is treated as prerelease and `pl` as postrelease. Actually, both dates are snapshots and should be ignored.

**Comment by blshkv** [comment]
We use _pre for pre-release and _p for post release. Please fix this logic for gentoo

**Comment by blshkv** [comment]
https://devmanual.gentoo.org/ebuild-writing/file-format/index.html

It will be useful for cases like that one:
https://repology.org/metapackage/pyrit/versions

Gentoo has a stable release (2016) but we provide the latest _p with few recent changes
