### ISSUE TITLE
skim-fuzzy-finder/skim-unclassified to skim

### ISSUE THREAD

**Issue by Neustradamus** [repology/repology-rules#884]
Dear @AMDmi3,

The project has a new place: https://github.com/skim-rs/skim

**Projects affected**
skim-fuzzy-finder
https://repology.org/project/skim-fuzzy-finder

skim-unclassified
https://repology.org/project/skim-unclassified

**Observed behavior**
It is currently skim-fuzzy-finder and skim-unclassified but not good.

**Expected behavior**
Can you rename skim-fuzzy-finder to skim and merge skim-unclassified into?

Thanks in advance.

**Comment by AMDmi3** [comment]
> Can you rename skim-fuzzy-finder to skim

No, because the name is used by 3 projects

**Comment by Neustradamus** [comment]
Have you updated the new place?
- https://github.com/skim-rs/skim

At the same time, maybe you can name "skim-rs".

**Comment by AMDmi3** [comment]
`skim-rs` is unfortunately not descriptive for the case when user discovers that the name is ambiguous and he needs to choose the right project.
