### ISSUE TITLE
OCL-dev/OpenCL-ICD-Loader vs KhronosGroup/OpenCL-ICD-Loader

### ISSUE THREAD

**Issue by FabioLolix** [repology/repology-rules#903]
Hi, looking further into OpenCL-ICD-Loader there are 2 implementations; one by `OCL-dev` and one by `KhronosGroup`

* https://github.com/OCL-dev/ocl-icd
* https://github.com/KhronosGroup/OpenCL-ICD-Loader

* `ocl-icd` is by OCL-dev https://repology.org/project/ocl-icd/versions
* `opencl-icd` is mixed https://repology.org/project/opencl-icd/versions
* `opencl-icd-loader` is mixed https://repology.org/project/opencl-icd-loader/versions
* plus `khronos-ocl-icd` and `khronos-ocl-icd-loader` https://repology.org/projects/?search=khronos-ocl-icd&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=

I don't have the knowledge to split e merge this

**Comment by AMDmi3** [comment]
`khronos-ocl-icd-loader` -> `ocl-icd-loader` seem to be the only valid merge, other packages are misnamed and will not be handled in repology.
